### PR TITLE
Update MFC key dictionary

### PR DESCRIPTION
**Pull request by jblanked**
# What's new

- Implemented MFC keys from https://github.com/ikarus23/MifareClassicTool/blob/master/Mifare%20Classic%20Tool/app/src/main/assets/key-files/extended-std.keys

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by equipter** [comment]
a lot of these are not validated as static in any way. "some random card" being the origin for one of these is scary enough. 

just because they're from MCT doesn't make them reliable enough to blindly merge imo.

**Comment by noproto** [comment]
We need verified static keys, these are not and will only offset the improvements we just made in MFC. PM3 has many verified static keys and it's a good reference dictionary to use.

**Comment by WillyJL** [comment]
> We need verified static keys, these are not and will only offset the improvements we just made in MFC. PM3 has many verified static keys and it's a good reference dictionary to use.

last time i checked a couple months ago, pm3 dictionary is a superset of mct dictionary. that is to say, everything from mct is in pm3 dict, plus pm3 one has more.

EDIT: nevermind, there are 19 total keys that are in mct dict and not in pm3. still, considering that pm3 has roughly 2000 keys 19 is so little that IMO this argument of "we should trust pm3 instead of mct" might not mean much.

**Comment by onovy** [comment]
See my proposal in #4013

**Pull request closed without merging**
