### PR TITLE
Proper Lock With Pin if Pin is set

### PR DESCRIPTION
**Pull request by RogueMaster**
# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by RogueMaster** [comment]
#1186 will be resolved with this I think

**Comment by skotopes** [comment]
Breaks qFlipper / Cli+VCP

**Comment by skotopes** [comment]
It's actually quite complex tasks. The reason why we keep current behaviour is because it requires a lot more complex system to manage state transitions and special cases (update).

**Comment by RogueMaster** [comment]
qFlipper / Cli+VCP doesn't have access to the locked device. Makes sense. Wouldn't this have been done intentionally? Is there a status that can be checked to see if there is an active qFlipper or Cli+VCP connection?

**Comment by skotopes** [comment]
> qFlipper / Cli+VCP doesn't have access to the locked device. Makes sense. Wouldn't this have been done intentionally? Is there a status that can be checked to see if there is an active qFlipper or Cli+VCP connection?

nope and that was the main stopper

**Comment by RogueMaster** [comment]
Is there something that can be checked to see if it is plugged into USB?

**Comment by RogueMaster** [comment]
Could disable locking while charging perhaps...  if(power->state == PowerStateCharging)

**Comment by skotopes** [comment]
> Is there something that can be checked to see if it is plugged into USB?

yes, but that's not that simple. We have locking refactoring in backlog. Basically it need to be redone with fixes for all special cases.

If you want to do it, then start from diagramming current locking scheme, then ping me for review, then I can help you we redesigning it and splitting into coding tasks.

**Comment by skotopes** [comment]
There were a bug in locking, fixed in https://github.com/flipperdevices/flipperzero-firmware/pull/1245 please check if it works for you

**Comment by RogueMaster** [comment]
> > Is there something that can be checked to see if it is plugged into USB?
> 
> yes, but that's not that simple. We have locking refactoring in backlog. Basically it need to be redone with fixes for all special cases.
> 
> If you want to do it, then start from diagramming current locking scheme, then ping me for review, then I can help you we redesigning it and splitting into coding tasks.

I'm not sure how it needs to be refactored, or why. Sorry. I think I'll need more understanding of the right calls in Flipper for this. I've been searching around the code for examples on everything I've worked on. I'll try to add a power state check for my auto-lock on pin. Let me know if I should submit those updates

**Pull request closed without merging**
