### PR TITLE
Add support for Pioneer SR IR remotes

### PR DESCRIPTION
**Pull request by radioegor146**
# What's new

- Added support for the Pioneer SR IR remotes

# Verification 

- Read Pioneer SR IR remote command
- Send command to some piece of Pioneer hardware with SR support

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
@radioegor146 can you also add unit tests to https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/debug/unit_tests/infrared/infrared_test.c ?

**Comment by radioegor146** [comment]
Working on it!

**Comment by radioegor146** [comment]
@skotopes does infrared testset work currenly? Because as I try to run `unit_tests infrared` Flipper just hangs (even w/o my changes).

**Comment by skotopes** [comment]
> @skotopes does infrared testset work currenly? Because as I try to run `unit_tests infrared` Flipper just hangs (even w/o my changes).

Yes, all PRs are going through unit tests.
Most likely you forgot to upload unit test assets.

**Comment by skotopes** [comment]
@gsurkov can you do review?

**Comment by gsurkov** [comment]
@radioegor146 Is there any progress on unit tests? Do you need help with that?

**Comment by radioegor146** [comment]
Thanks for helping with tests

**Comment by gsurkov** [comment]
@radioegor146 I've modified the decoder a bit so that it would accept the input from its own encoder (it wasn't the case due to different stop bit handling in either of them)

**Review by skotopes — APPROVED** [review]

**Comment by Cgomez664** [comment]
I need help understanding everithing but I really what I see  can somebody take there time and help me I promise I will make I back to you and I just got my flipper and I want to learn how to use it

**Comment by skotopes** [comment]
> I need help understanding everithing but I really what I see can somebody take there time and help me I promise I will make I back to you and I just got my flipper and I want to learn how to use it

http://docs.flipper.net

**Pull request merged**
