### PR TITLE
nfc: make dict attack more interactive

### PR DESCRIPTION
**Pull request by indutny**
# What's new

- Progress bar in nfc dict attack mode would tick not just with scanned sectors, but with used dictionary keys

# Verification 

- Scan mifare classic key

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by indutny** [comment]
In lieu of closed PR: https://github.com/flipperdevices/flipperzero-firmware/pull/1443

cc @skotopes

**Comment by indutny** [comment]
I realized that I need to make it account properly for the size of user dict. Will un-draft the PR as soon as it is done.

**Comment by indutny** [comment]
Nevermind, that was a night time and I didn't realize that we actually reset the UI when working through a new dict. Force pushed and ready for a review now. Sorry for the noise!

**Comment by gornekich** [comment]
Hello @indutny . Nice work, thank you!
Please, format sources. You can run ./fbt format.
We will merge your PR after 0.63 release (this week)

**Comment by indutny** [comment]
TIL! Thanks.

**Review by gornekich — APPROVED** [review]
Thanks!

**Review by skotopes — APPROVED** [review]

**Comment by indutny** [comment]
Awesome. Thank you!

**Pull request merged**
