### PR TITLE
input_srv: Put input state data on the stack of the service

### PR DESCRIPTION
**Pull request by CookiePLMonster**
# What's new

`input_srv` did two allocations on startup that span the entire lifetime of the service, and thus the entire session. Since this service has a 1KB stack, let's make use of that by putting this data on the stack instead.

# Verification 

Verify that input still works.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
@hedger With these changes in place, should `input_i.h` go? `input_cli` does not need the `Input` structure anymore, and so the entire contents of this file could be moved to `input.c`.

**Comment by hedger** [comment]
@CookiePLMonster I think so - since now we can pass pubsub pointer to CLI code.

**Comment by CookiePLMonster** [comment]
> @CookiePLMonster I think so - since now we can pass pubsub pointer to CLI code.

Done.

**Comment by CookiePLMonster** [comment]
I now made the `counter` start from `1` and not `0`, as I realized that lets me use post-increment rather than pre-increment while keeping the behaviour unchanged.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
