### PR TITLE
[DRAFT/WIP] added ISO15693 reading, saving and revealing from privacy mode (unlock)

### PR DESCRIPTION
**Pull request by g3gg0**
# What's new

- Added NfcV through various layers
- Added NfcV memory and system info reading
- Added loading/saving
- Added unlocking NfcV NXP SLIX-L (reveal from privacy mode)

# Purpose

This is a **draft / WIP**, being aware that:
- Scenes are not clean or thought-through well I guess
- rfalNfcv* calls are being made from lib/ level
- big API change pending

Just to show whats happening.

### CODE REVIEW

**Comment by Astrrra** [comment]
Hi, please convert the PR to a draft via Github tools, as it's currently in the "Open" state

**Comment by g3gg0** [comment]
ah, great. didn't know that. done :)

**Comment by g3gg0** [comment]
As already discussed in Telegram the file format code might need some updates.
This can be done without any effect on existing files, however the code might need some update in future.

Of couse we can implement it "flat" with just a single enum, but on the long run this might end in a mess.

Here a visualization of how "hierarchical" it is/will get:
grafik

**Comment by Enteee** [comment]
This pull request would be a great addition, I have tested this briefly with several cards. Reading seems to work fine, but I could not get the emulation to work properly. Namely, the emulated cards were not accepted by any devices I tested them with. Sadly I don't have the hardware required to debug this further.

**Comment by g3gg0** [comment]
@Enteee
Yeah this is likely if the reader uses AM instead of OOK.
The ST should support AM in transparent mode, it's just not documented.
The chip is said to modulate the IRQ line instead of MISO, but for some reason that doesnt work. 
Maybe some register settings, we'll see. 

Currently investigating this with a guy who wants to emulate picopas. Thats also the reason why i reworked the code a bit lately. 

Also see:
https://community.st.com/s/question/0D73W000001oEvPSAU/detail

**Comment by ZAM-** [comment]
Tested the ISO15693 emulation with Ikon ski pass and it worked! Any idea if/when writing would be implemented? @g3gg0

**Comment by g3gg0** [comment]
hi, great to hear that.
what do you want to write where?
just copy content to another card?

the UID of a card is not changeable btw.

**Comment by ZAM-** [comment]
@g3gg0 Yes I would just like to copy to another card without changing UID.

**Comment by g3gg0** [comment]
i see.
currently i didn't plan this, but good point.

**Comment by NotRQYALTY** [comment]
May i ask i have ISO15693 SLIX i tried with rouge master firmware it detects it and save it but when i emulate nothing happens,how can i try this code/firmware to my flipper ,im sorry I'm new to this,Thank you.

**Comment by team-orangeBlue** [comment]
you ask the reliability (current reliability: 0%) of rogue master to rogue master

or be a good boy and dont get close to it

**Comment by NotRQYALTY** [comment]
> you ask the reliability (current reliability: 0%) of rogue master to rogue master
> 
> or be a good boy and don't get close to it

so what's the best firmware for the flipper? tbh i only bought it for opining my safe's and garage door and it didn't open any of my safe's,they told me rogue master is the best and for me it only crashes and detects my nfc-v and save it and the emulation didn't do anything

**Comment by pcunning** [comment]
This pull request is not the place for Q&A or help. If you would like to discuss other firmware go discuss it on their GitHub. Please keep discussion to code and implementation of the given PR. 

Additionally if you are using the functionality of this PR in another firmware there is probably a reason it is not merged here yet and they were premature in merging it into their codebase.

**Comment by alvarotorijano** [comment]
Hi, nice work! I have been waiting for this feature since some time ago. I would like to mention that this type of cards are not listed in the "extra actions -> read specific card type" inside the NFC main app. Would be great to add it to this menu!

**Comment by neich03** [comment]
community gives thanks for your great job! NFC-V is so important! i can´t believe F0 team didn´t work more on it... every step forward is hugely appreciated!. thanks!

**Comment by bettse** [comment]
@neich03 

> NFC-V is so important! i can´t believe F0 team didn´t work more on it

Firstly, this is not related to the PR and development, which as mentioned, should be avoided.  Secondly, your phrasing can be seen as diminishing the Flipper Zero team when they are very very hard at work and have to prioritize the various subsystems the flipper zero has.  Stick to statements of excitement and avoid statements that can be seen as critical.

If you would delete your comment to clean up the PR, I will follow by deleting this reply.

**Comment by g3gg0** [comment]
> @neich03
> 
> > NFC-V is so important! i can´t believe F0 team didn´t work more on it
> 
> Firstly, this is not related to the PR and development, which as mentioned, should be avoided. Secondly, your phrasing can be seen as diminishing the Flipper Zero team when they are very very hard at work and have to prioritize the various subsystems the flipper zero has. Stick to statements of excitement and avoid statements that can be seen as critical.
> 
> If you would delete your comment to clean up the PR, I will follow by deleting this reply.

while i agree that this is not for unrelated discussion, i do not get why this comment should be critical.
noone was insulted and this comment wasnt unreasonably unfriendly.

just explain to him that 
"NfcV is not that widespread and they focused other things first and he should't worry."
and "things will take its time and good developers can't work faster even with more money."

forbidding that kind of questioning is something i dont expect from open source projects.

topic:
draft-PR closed, will create another one from another branch

**Comment by neich03** [comment]
> @neich03
> 
> > NFC-V is so important! i can´t believe F0 team didn´t work more on it
> 
> Firstly, this is not related to the PR and development, which as mentioned, should be avoided. Secondly, your phrasing can be seen as diminishing the Flipper Zero team when they are very very hard at work and have to prioritize the various subsystems the flipper zero has. Stick to statements of excitement and avoid statements that can be seen as critical.
> 
> If you would delete your comment to clean up the PR, I will follow by deleting this reply.

just wanted to give thanks to those who work for NFC-V working in the future. And love for F0 team as well. just wondering why something with so many applications is not tagged as priority. but of course, not my business. just thanks to all!

**Comment by skotopes** [comment]
NFC Hal is currently being rewritten, we'd like to finalize low level before switching to "V". Also team is currently on vacation we'll resume normal merge flow in next couple days.

**Comment by ImSwifted** [comment]
Top

**Comment by alvarotorijano** [comment]
Highly apreciated. Would be great to be able to write data to the card, editing dump, writing dumped data, etc

**Comment by MadjidZ** [comment]
Hello @g3gg0

I tested this branch on my FZ.

Read and emulate NFCV are ok but the reader does not react by offering him the emulator card from the FZ.

I therefore wonder about the emulation which seems incorrect. I have to try to copy the FZ card to a real SLI/SLIX UID card that can be found here:
https://lab401.com/fr/products/icode-sli-slix-compatible-uid-modifiable?_pos=10&_sid=0a2e4b59f&_ss=r

If you want to take a look at the copy of the NFC-V card (copy-nfc-v-iso15963.nfc) with which I tested it is available here: https://file.io/AeR1zNkIFpis

Thank you for advancing the reading of NFC-V

**Comment by g3gg0** [comment]
grafik

also: did you use this stale, old branch or the [PR](https://github.com/flipperdevices/flipperzero-firmware/pull/2316)?

**Comment by MadjidZ** [comment]
Sorry for expired link, i upload another here : https://easyupload.io/z7eqgt

I test  branch "ISO15693" of https://github.com/g3gg0/flipperzero-firmware.git

I got the source via git, then built the dfu via fbt

**Comment by g3gg0** [comment]
I don't get it, why do you comment on a totally different branch?

go and test this one: https://github.com/flipperdevices/flipperzero-firmware/pull/2316

**Pull request closed without merging**
