### PR TITLE
weather_station: add oregon3 protocol support with THGR221

### PR DESCRIPTION
**Pull request by clashlab**
# What's new

- Add support for Oregon3 protocol

# Verification 

- Tested with a THGR221 probe
thgr221

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by hedger** [comment]
Can you please provide a RAW signal with sample data?

**Comment by clashlab** [comment]
> Can you please provide a RAW signal with sample data?

Attached are 2 RAW files (renamed from sub to txt)
- channel: 1, temp: 27.6°C, RH: 61%
[Ch1_276_61.txt](https://github.com/flipperdevices/flipperzero-firmware/files/11702722/Ch1_276_61.txt)
- channel: 2, temp: 27.9°C, RH: 75%
[Ch2_279_75.txt](https://github.com/flipperdevices/flipperzero-firmware/files/11702723/Ch2_279_75.txt)

**Review by skotopes — APPROVED** [review]

**Comment by wosk** [comment]
It brings false Oregon3 signals
[IMG_20230616_124212_551.png](https://github.com/flipperdevices/flipperzero-firmware/assets/1042932/c8fc5c89-84b5-4993-a71a-6a7586eeedd3)

Don't pay attention to frequency - hopping was enabled.

One more link 
https://t.me/flipperzero_unofficial_ru/105577?single

**Comment by skotopes** [comment]
@wosk can you provide SubGhz RAW recordings?

**Comment by wosk** [comment]
> @wosk can you provide SubGhz RAW recordings?

I don't own a source device of that signals, so I can't get RAW and see the false signals simultaneously.
The second device I have - Msi.SDR. Will try with that

**Comment by clashlab** [comment]
We can only report supported sensors.

[Make the default case return 0](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/external/weather_station/protocols/oregon3.c#L119)

**Pull request merged**
