### PR TITLE
Print card CID in storage info

### PR DESCRIPTION
**Pull request by hramrach**
Add a wrapper around SD_GetCIDRegister that initializes the SPI bus and use it to get the CID info.

Issue #2214

Signed-off-by: Michal Suchanek <msuchanek@suse.de>

# What's new

- Shows SD card identification in storage info

# Verification 

- External storage info in cli and UI should include SD card identification data

cid2

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by hramrach** [comment]
apparently conflicts with #2204

**Comment by hramrach** [comment]
Note: using uppercase hexadecimal digits which is consistent with manufacturers using uppercase letters for the product name.

**Comment by skotopes** [comment]
Yep it does conflict with #2204, @DrZlo13 is currently working on new SD driver which will replace one you've edited.
I'll leave final decision to @DrZlo13.

**Comment by skotopes** [comment]
@DrZlo13 this PR is still waiting for your comment )

**Comment by DrZlo13** [comment]
That pr is ready to merge

**Review by skotopes — APPROVED** [review]

**Pull request merged**
