### PR TITLE
Assets: correct MicroSD card pinout in service animations

### PR DESCRIPTION
**Pull request by DXVVAY**
# What's new

- Assets: correct MicroSD card pinout in service animations

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by hedger — DISMISSED** [review]

**Comment by hedger** [comment]
Nice attention to detail.

**Comment by DXVVAY** [comment]
> Nice attention to detail.

Thx I noticed this while I was making some new assets for my firmware

**Comment by skotopes** [comment]
Technically speaking micro-sd got 1 pin less than we have it on the picture. If you want to show real micro-sd then it must be changed too.

Un-draft when ready

**Comment by DXVVAY** [comment]
> Technically speaking micro-sd got 1 pin less than we have it on the picture. If you want to show real micro-sd then it must be changed too.
> 
> 
> 
> Un-draft when ready

Yep I'll be on it as soon as I get on my pc

**Review by skotopes — CHANGES_REQUESTED** [review]
On L0_Url_128x51 and L0_NoDb_128x51 magnifying glass is too close to the right side of the card. Can you shift it 1 pixel left?

**Comment by DXVVAY** [comment]
> On L0_Url_128x51 and L0_NoDb_128x51 magnifying glass is too close to the right side of the card. Can you shift it 1 pixel left? 
> 
> 

Yes sure i Will du it asap

**Comment by DXVVAY** [comment]
> magnifying glass

its updated now if there is any other problems let me know

**Comment by skotopes** [comment]
Now it being trimmed on the right edge. Why not to just move magnifying glass 1px left as I've mentioned in review?

**Comment by DXVVAY** [comment]
> t being trimmed on the right edge. Why not to just move magnifying glass 1px left as I'

yes i did move it i did not trim it

**Comment by DXVVAY** [comment]
> Now it being trimmed on the right edge. Why not to just move magnifying glass 1px left as I've mentioned in review?

you could use the onion skin option to have a easier look because one pixel is not that easy to notice lmao

**Comment by skotopes** [comment]
> > t being trimmed on the right edge. Why not to just move magnifying glass 1px left as I'
> 
> yes i did move it i did not trim it

In that case icon was damaged on previous steps.
Just compare frames 1 and 2 in L0_Url_128x51 between original and your version.

**Comment by DXVVAY** [comment]
> > > t being trimmed on the right edge. Why not to just move magnifying glass 1px left as I'
> > 
> > 
> > yes i did move it i did not trim it
> 
> In that case icon was damaged on previous steps. Just compare frames 1 and 2 in L0_Url_128x51 between original and your version.

let me take a look

**Comment by DXVVAY** [comment]
> > > t being trimmed on the right edge. Why not to just move magnifying glass 1px left as I'
> > 
> > 
> > yes i did move it i did not trim it
> 
> In that case icon was damaged on previous steps. Just compare frames 1 and 2 in L0_Url_128x51 between original and your version.

I am sorry but i do not see the problem here what was damaged I had to trim the sd card so I would be able to remove one of the pins if that is the problem, here are the animations compiled as a gif
ezgif com-gif-maker (30)
ezgif com-gif-maker (29)

**Comment by DXVVAY** [comment]
> > > > t being trimmed on the right edge. Why not to just move magnifying glass 1px left as I'
> > > 
> > > 
> > > yes i did move it i did not trim it
> > 
> > 
> > In that case icon was damaged on previous steps. Just compare frames 1 and 2 in L0_Url_128x51 between original and your version.
> 
> I am sorry but i do not see the problem here what was damaged I had to trim the sd card so I would be able to remove one of the pins if that is the problem, here are the animations compiled as a gif ezgif com-gif-maker (30) [ ezgif com-gif-maker (30) ](https://user-images.githubusercontent.com/89728480/215320133-9494d72c-f8d0-49e8-b494-579d6b4c6701.gif) [ ](https://user-images.githubusercontent.com/89728480/215320133-9494d72c-f8d0-49e8-b494-579d6b4c6701.gif) ezgif com-gif-maker (29) [ ezgif com-gif-maker (29) ](https://user-images.githubusercontent.com/89728480/215320140-290eff3c-1c64-4110-85af-2ee6b9e35b70.gif) [ ](https://user-images.githubusercontent.com/89728480/215320140-290eff3c-1c64-4110-85af-2ee6b9e35b70.gif)

oh I'm sorry I just saw the problem will fix it now

**Comment by DXVVAY** [comment]
> > > t being trimmed on the right edge. Why not to just move magnifying glass 1px left as I'
> > 
> > 
> > yes i did move it i did not trim it
> 
> In that case icon was damaged on previous steps. Just compare frames 1 and 2 in L0_Url_128x51 between original and your version.

Is this better now? again if there was any other problems let me know
ezgif com-gif-maker (32)
ezgif com-gif-maker (31)

**Comment by skotopes** [comment]
Yep. Looks good.

**Review by skotopes — APPROVED** [review]

**Comment by DXVVAY** [comment]
> Yep. Looks good.

happy to contribute!

**Comment by skotopes** [comment]
> > Yep. Looks good.
> 
> happy to contribute!

Thanks for contribution ;-)

**Pull request merged**
