### PR TITLE
sk-SK maping keybord for BadUsb and AC.ir

### PR DESCRIPTION
**Pull request by jaroslavmraz**
# What's new

- Adding sk-SK mapping for keybord bad usb function `https://github.com/flipperdevices/flipperzero-firmware/pull/1525#issuecomment-1204223661`

And AC.ir - first beta of Universal RC for AirConditioner brutforce (Beta only POWER) but will add more after you crate tempalte.

# Verification 

- After implementing feature from PR you can add maping file and change keybord to SK language to run duckycode. And after implementing Uni AC ir you can test it on AC device from list.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
Hi. Couple notes:
- 1 pull request - 1 feature
- We currently don't accept remotes for air conditioners. They are stateful devices and we still trying to figure out what do with it.
- As for sk mapping, we'll merge it after #1525

**Comment by jaroslavmraz** [comment]
Ok. Noted.

**Comment by xMasterX** [comment]
Hi, you should close this PR and open new with only your changes, as I see you trying to merge entire eng1n33r fork into official repo here, you should not do that

**Comment by jaroslavmraz** [comment]
as request closing and will open new

**Comment by jaroslavmraz** [comment]
> Hi, you should close this PR and open new with only your changes, as I see you trying to merge entire eng1n33r fork into official repo here, you should not do that

ok i Had crate new. https://github.com/flipperdevices/flipperzero-firmware/pull/1619

**Pull request closed without merging**
