### PR TITLE
oregon2 additional sensors

### PR DESCRIPTION
**Pull request by merlokk**
# What's new

- added a list of sensors 
- added several additional temperature and temperature/humidity sensor id's

# Verification 

- code has almost no changes
- or check with sensors (

# Checklist (For Reviewer)

- [x] PR has a description of the feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device, and verified the feature/bugfix

### CODE REVIEW

**Comment by merlokk** [comment]
image

**Comment by skotopes** [comment]
@merlokk  please attach RAW files with new sensors to this PR

**Comment by merlokk** [comment]
i have only one sensor from them. all the rest added from https://github.com/merbanan/rtl_433/blob/master/src/devices/oregon_scientific.c
I can send the file from URH via telegram/etc. here it cant be added(

**Comment by skotopes** [comment]
> i have only one sensor from them. all the rest added from https://github.com/merbanan/rtl_433/blob/master/src/devices/oregon_scientific.c
> I can send the file from URH via telegram/etc. here it cant be added(

Github gist will be the best option. Or ping me on discord.

**Comment by Skorpionm** [comment]
without records of real sensors, checking the code is impossible, since there are often moments that were not taken into account when writing the code, especially when porting the code to the blind

**Comment by merlokk** [comment]
yes.
this PR just adds some device IDs that are publicly known and added to multiple repositories on GitHub

**Review by skotopes — APPROVED** [review]

**Comment by michelinok** [comment]
> i have only one sensor from them. all the rest added from https://github.com/merbanan/rtl_433/blob/master/src/devices/oregon_scientific.c I can send the file from URH via telegram/etc. here it cant be added(

PLEASE Can you send the file to me? my email is  costantino.michele@gmail.com
If the file is big, you can use wetransfer.

Many thanks!

**Comment by merlokk** [comment]
cant( gmail blocking archives with passwords and files from URH
it will lay here for several days
https://drive.google.com/file/d/1zmgdfgKbg9FRe3mxirnVpjUZnmEHrsJk/view?usp=sharing

**Pull request merged**
