### PR TITLE
Oregon2 extra

### PR DESCRIPTION
**Pull request by Shmuma**
# What's new

- Fixed protocol type and flags
- Added support of sensor 1D20 (temperature + humidity)

# Verification 

- Capture data from 1D20 or EC40 sensors

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
@Shmuma can you also provide raw record for tests?

**Comment by Shmuma** [comment]
> @Shmuma can you also provide raw record for tests?

If I’m not mistaken, WeatherStation FAP has no unit tests yet.
I can add raw records to the subghz tests, but WeatherStation protocols are not loaded in general subghz 
protocols, so, they won’t be executed.

**Comment by Shmuma** [comment]
Added two raw recordings from my sensors.

**Comment by skotopes** [comment]
@Shmuma those are for our QA. We'll add unit tests for external applications in future

**Review by skotopes — APPROVED** [review]

**Comment by RocketGod-git** [comment]
AcuRight 606TX arriving tomorrow for testing.

**Pull request merged**
