### PR TITLE
Troyka parser improvements

### PR DESCRIPTION
**Pull request by assasinfil**
# What's new

- Rewrited troyka parser
- All known Mosgortrans layouts have been added

# Verification 

- Try to parse Troyka card and validate result with "Транспортные карты Москвы"

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by gornekich** [comment]
Thanks for PR!
Please run linter: ./fbt format

Also we will merge this PR after #3365

**Comment by assasinfil** [comment]
Waiting for accept these pr https://github.com/flipperdevices/flipperzero-firmware/pull/3386, https://github.com/flipperdevices/flipperzero-firmware/pull/3383

**Comment by gornekich** [comment]
@assasinfil thanks for update!
I really like adding mosgorrtrans_util to application API. I guess this API will be reused for other plugins, right?

I tested this plugin with some of my cards and it looks good. I think it's a little bit confusing to see other types of cards like "Ediniy" and "TAT" even there is "No ticket". I guess this means that the card is configured the way it can be used as "Ediniy", but there is no ticket yet, right?

@Astrrra could you please test this PR with your cards and leave you feedback?

**Comment by assasinfil** [comment]
@gornekich Other types of cards are actually present in Troyka. Of course, I haven't seen the opportunity to write down a single one for a long time, but there is one for reading old cards)

**Review by gornekich — DISMISSED** [review]

**Review by skotopes — APPROVED** [review]

**Pull request merged**
