### PR TITLE
Improved build flags and startup ASM directives

### PR DESCRIPTION
**Pull request by IComplainInComments**
# What's new

Improved hardware compilation
Anecdotal notice of improved startup speeds and faster function in general.
- Will post benchmarks if I am given a way on how to properly benchmark 

# Verification 

Compile and install

# Checklist (For Reviewer)

- [X] PR has description of feature/bug or link to Confluence/Jira task
- [X] Description contains actions to verify feature/bugfix
- [X] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by IComplainInComments** [comment]
Just to add I am the person @hedger was talking with on Discord about this same topic.

**Comment by skotopes** [comment]
Not sure where did you get it, but wb series datasheet explicitly tells that used FPU is single precision (fpv4-sp-d16).
FPU is intentionally not used at startup: nor it needed at that point, nor error can be handled correctly.
All other changed options are also incorrect.

**Comment by IComplainInComments** [comment]
> Not sure where did you get it, but wb series datasheet explicitly tells that used FPU is single precision (fpv4-sp-d16).
> FPU is intentionally not used at startup: nor it needed at that point, nor error can be handled correctly.
> All other changed options are also incorrect.

D16 is used when there are ONLY 16 FPU registers, the register diagram for the chip from WB was used for this answer. Including looking up the specific model and diagram sheet, along with its assembly sheet.

Using that optimization is not for this chip.

Furthermore the chip is THUMB2 compliant, meaning that in the UAL spec would allow use of the hardware FPU and not relying on a library, reducing the size of the code.

I am more than welcome to do any testing you wish, but I did a few hours of research to make sure this setup was correct. And I can say without a shadow of a doubt that d16 is not for this chipset, as we have 32 FPU registers and not 16.

**Comment by skotopes** [comment]
D16 in this context means: double 16 - single 32

**Comment by IComplainInComments** [comment]
> D16 in this context means: double 16 - single 32

ARM themselves say that the cortex-M4 with a single float point resolve to vfpv4-sp which resolves to vfpv4+fp for the GCC options

EDIT: forgot link https://developer.arm.com/documentation/dui0472/k/Compiler-Coding-Practices/Processors-and-their-implicit-Floating-Point-Units--FPUs-

**Comment by skotopes** [comment]
Can I see documents about it? 

Because DDI0403E_e_armv7m_arm.pdf that you mentioned in discord states different things in Table A1-1 Floating-point Extension full characterizations.

**Comment by IComplainInComments** [comment]
> Can I see documents about it?
> 
> Because DDI0403E_e_armv7m_arm.pdf that you mentioned in discord states different things in Table A1-1 Floating-point Extension full characterizations.

Here is the link to the PDF: https://www.st.com/resource/en/programming_manual/pm0214-stm32-cortexm4-mcus-and-mpus-programming-manual-stmicroelectronics.pdf

My PDF reader says page 252 for where to begin

EDIT: For the GCC option resolve link: https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html

because the arch is armv7e-m (Because arm states cortex-m4 supports virtualization instructions) the compiler has the extensions listed there, which for our case would be +fp

**Comment by skotopes** [comment]
Doesn't looks like they use same terms that are used in gcc.
I'd stick to ARM and GCC manuals and source code. 

At least we agree that this MCU have s32 and d16 with single precision and it is fpv4

**Comment by DrZlo13** [comment]
DDI0403E_e_armv7m_arm.pdf:
"Armv7-M fpu is FPv4-SP-D16-M for single precision (**_16 doubleword registers_** with single word precision)."

WB55 datasheet:
"The Cortex-M4F FPU implements the FPv4-SP floating-point extension ... The FPU contains 32 single-precision extension registers, which you can also access as **_16 doubleword registers_** for load, store, and move operations."

VFPv4 has 32 64-bit FPU registers, so mfpu=vfpv4 is wrong.

**Comment by skotopes** [comment]
And once again armv7e-m is different architecture.

I guess we can stop here.

**Comment by IComplainInComments** [comment]
> DDI0403E_e_armv7m_arm.pdf: "Armv7-M fpu is FPv4-SP-D16-M for single precision (**_16 doubleword registers_** with single word precision)."
> 
> WB55 datasheet: "The Cortex-M4F FPU implements the FPv4-SP floating-point extension ... The FPU contains 32 single-precision extension registers, which you can also access as **_16 doubleword registers_** for load, store, and move operations."
> 
> VFPv4 has 32 64-bit FPU registers, so mfpu=vfpv4 is wrong.

Also from the data sheet

"The FPv4-SP FPU supports:
• FP extension registers that software can view as either 32 single-precision or 16 double-precision registers.
• Single-precision floating-point arithmetic.
• Conversions between integer, single-precision floating-point, and half-precision floating-point formats.
• Data transfers of single-precision and double-precision registers."

**• Single-precision floating-point arithmetic.**
**• Conversions between integer, single-precision floating-point, and half-precision floating-point formats.**

**Comment by IComplainInComments** [comment]
> And once again armv7e-m is different architecture.
> 
> I guess we can stop here.

st literally says the cortex-m4 is Armv7e-M

Link: https://www.st.com/content/st_com/en/arm-32-bit-microcontrollers/arm-cortex-m7.html

**Comment by IComplainInComments** [comment]
I also want to just say im not trying to argue with you guys at this point, but to figure out who is correct here, because a lot of information is apparently either poorly documented, renamed, or flat out not described anywhere.

**Comment by skotopes** [comment]
> > And once again armv7e-m is different architecture.
> > I guess we can stop here.
> 
> st literally says the cortex-m4 is Armv7e-M
> 
> Link: https://www.st.com/content/st_com/en/arm-32-bit-microcontrollers/arm-cortex-m7.html

You literally gave link to m7 series.

**Comment by IComplainInComments** [comment]
> > > And once again armv7e-m is different architecture.
> > > I guess we can stop here.
> > 
> > 
> > st literally says the cortex-m4 is Armv7e-M
> > Link: https://www.st.com/content/st_com/en/arm-32-bit-microcontrollers/arm-cortex-m7.html
> 
> You literally gave link to m7 series.

Oh jesue christ you're right. let me double check something.

**Comment by IComplainInComments** [comment]
> > > And once again armv7e-m is different architecture.
> > > I guess we can stop here.
> > 
> > 
> > st literally says the cortex-m4 is Armv7e-M
> > Link: https://www.st.com/content/st_com/en/arm-32-bit-microcontrollers/arm-cortex-m7.html
> 
> You literally gave link to m7 series.

Sorry about that: https://www.st.com/content/st_com/en/arm-32-bit-microcontrollers/arm-cortex-m4.html

**Comment by DrZlo13** [comment]
> st literally says the cortex-m4 is Armv7e-M
> 
> Link: https://www.st.com/content/st_com/en/arm-32-bit-microcontrollers/arm-cortex-m7.html

I cannot find modern version of [that doc](https://launchpadlibrarian.net/177524521/readme.txt), but from there
-mthumb -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 will use armv7e-m/fpu architecture and I suspect nothing has changed since then.

**Comment by IComplainInComments** [comment]
> > st literally says the cortex-m4 is Armv7e-M
> > Link: https://www.st.com/content/st_com/en/arm-32-bit-microcontrollers/arm-cortex-m7.html
> 
> I cannot find modern version of [that doc](https://launchpadlibrarian.net/177524521/readme.txt), but -mthumb -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 will use armv7e-m/fpu arch

I put in the wrong link, its this one: https://www.st.com/content/st_com/en/arm-32-bit-microcontrollers/arm-cortex-m4.html

If you figured it out that you can go to the sidebar to change to m4 disregard this comment.

**Comment by IComplainInComments** [comment]
> > st literally says the cortex-m4 is Armv7e-M
> > Link: https://www.st.com/content/st_com/en/arm-32-bit-microcontrollers/arm-cortex-m7.html
> 
> I cannot find modern version of [that doc](https://launchpadlibrarian.net/177524521/readme.txt), but from there -mthumb -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 will use armv7e-m/fpu architecture and I suspect nothing has changed since then.

Alright now I think I know why -mfpu=fpv4-sp-d16 **IS CORRECT** its because the system also supports SIMD instructions as well, as systems that support partial NEON (Which DSP instructions is a subset) can use the d16 option.

Thank god we figured it out.

**Comment by skotopes** [comment]
I’ll check armv7e-m part at evening.

**Comment by IComplainInComments** [comment]
> I’ll check armv7e-m part at evening.

Ill compile a list for you to review to which support my conclusion. Ill reply back here with it.

**Comment by DrZlo13** [comment]
Okay, from [this document](https://launchpadlibrarian.net/177524521/readme.txt) we see that `-mthumb -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16` if it's enough to force the armv7e-m/fpu arch, so we don't need to specify -march.

From the datasheet we can see that the FPU contains s32 and d16 so obviously vfpv4 is wrong (s64 and d32) so what can we use? The GCC documentation only defines "vfpv4", "vfpv4-d16", "fpv4-sp-d16" and fpv4-sp-d16 (single precision with d16 access) the only one that suits us.

**Comment by DrZlo13** [comment]
Where am I wrong?

**Comment by IComplainInComments** [comment]
> Where am I wrong?

Im not saying you're wrong at all, im agreeing with you. 

What I am saying is it looks like there is a lot of confusion in deciding what was proper due to all the stupid naming conventions not having standard names for everything, or 0 explanation why something is named.

The confusion from me came from ARM saying to use vfpv4-sp which isnt an option in GCC, the d16 part was confusing because in it's descriptions it talked about use in the Cortex-A series, and I saw nothing about usage in the Cortex-M series till you posted that link.

Im just glad we reached to why we are armv7e-m, and I Just found the difference between armv7-m vs armv7e-m, its literally the DSP instructions only: https://community.arm.com/arm-community-blogs/b/architectures-and-processors-blog/posts/armv6-m-vs-armv7-m---unpacking-the-microcontrollers

Im just glad we figured out for sure what exact instruction set we are using, and which FPU to use based on real documentation and not recommendation. Ya know? Further up I realized it was obvious what I submitted wasnt completely valid, but we still argued back and forth if we were armv7e-m or armv7-m, and im glad we figured out which. As just finding this out will help others in their coding endeavors since we know the difference now.

**Comment by skotopes** [comment]
I'm not sure that armv7e-m option is needed mcpu + float point extension should automatically imply it. Anyway, I'll get back to it at evening.

**Pull request closed without merging**
