### PR TITLE
NFC: fix creating MF Classic tags from "Add Manually" menu (BCC calulation and ATQA/SAK writing)

### LINKED ISSUE #2341: Mifare classic 1k wrong bcc
### Describe the bug.

When you try create mifare classic 1k 4-byte uid card with add manually function tag creates with wrong bcc FF

### Reproduction

Add manually mifare classic 1k
IMG_20230129_003227_557

### Target

_No response_

### Logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AloneLiberty**
# What's new

- Write necessary data to tag (BCC/ATQA/SAK) when creating tag from menu "Add Manually" (BCC only for 4byte tags). Fixes https://github.com/flipperdevices/flipperzero-firmware/issues/2341

# Verification 

- Create "1k 4byte" tag from menu
- Write it to magic tag
- Check that tag is readable

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by gornekich** [comment]
Hello @AloneLiberty . Thanks for PR!

I tested it and it works fine. However nfc unit tests expect 0xff after uid in manufacturer block. That's not correct. Could you fix it? We can't merge your PR until all unit tests pass successfully.

To build firmware with unit test run
`./fbt FIRMWARE_APP_SET=unit_tests`

To run unit tests you should open CLI and run `unit_tests nfc`

**Review by gornekich — CHANGES_REQUESTED** [review]
Hello @AloneLiberty . Thanks for PR!

I tested it and it works fine. However nfc unit tests expect 0xff after uid in manufacturer block. That's not correct. Could you fix it? We can't merge your PR until all unit tests pass successfully.

To build firmware with unit test run
`./fbt FIRMWARE_APP_SET=unit_tests`

To run unit tests you should open CLI and run `unit_tests nfc`

**Comment by skotopes** [comment]
un-draft when ready

**Review by gornekich — APPROVED** [review]
Thank you!

**Review by skotopes — APPROVED** [review]

**Pull request merged**
