### PR TITLE
NFC: H World Hotel Chain Room Key Parser

### PR DESCRIPTION
**Pull request by zinongli**
# What's new

- A parser plugin for reading room number and check-in & expiration dates from a room key. 
- H World operates around 10k hotels and 1m rooms, most of which in mainland China. 
- The two types of keys (standard and VIP) are in fact used interchangeably. Both encoperate static key sets. 
- The parser helps with reading by including the static keys. It also verifies against the static keys before attempting to parse in order to prevent false positives.

# Verification 

- Read these two samples. 
[h_world_sample.zip](https://github.com/user-attachments/files/17368879/h_world_sample.zip)

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
@zinongli looks like we don't have keys for VIP card in the dictionary.

Opening card dump shows info, but reading emulated card goes through dictionary attack.

**Comment by zinongli** [comment]
@skotopes do you mind reopen this so I can add those three keys? I can make a separate PR but this might be more effcient.

**Comment by skotopes** [comment]
@zinongli its already merged ) New PR please

**Comment by zinongli** [comment]
Sure thing, PR is up

**Pull request merged**
