### PR TITLE
[IR] Heavily Expand Universal Remotes

### PR DESCRIPTION
**Pull request by jaylikesbunda**
# What's new

AC: 71.76% increase
Audio: 430.76% increase
Projector: 31.93% increase
TV: 34.32% increase
used: https://github.com/jaylikesbunda/F0-Universal-IR-Appender
pulled from: https://github.com/Lucaslhm/Flipper-IRDB

# Checklist (For Reviewer)

- [X] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by xMasterX** [comment]
How do you verify RAW remotes like ACs to not have duplicates or being fully incorrect in first place?
AC files in IRDB doesn't follow universal remote buttons, that require specific settings, you mapped some buttons and it will make universal ac remote random and wokring incorrectly, because someone in IRDB labeled button OFF as button ON
etc..

Have you talked with IRDB maintainers about how you can do it properly? Because in current condition it looks like adding random remotes without verification, and its not good idea as I think.


Also why do you filled checklist for reviewer, if you are PR author, not the reviewer?

**Comment by jaylikesbunda** [comment]
> How do you verify RAW remotes like ACs to not have duplicates or being fully incorrect in first place? AC files in IRDB doesn't follow universal remote buttons, that require specific settings, you mapped some buttons and it will make universal ac remote random and wokring incorrectly, because someone in IRDB labeled button OFF as button ON etc..

The mapping i've made tries to be very safe to avoid wrong matches with button renaming but I honestly didn't consider people labeling buttons to the wrong functions in the IRDB. It also hashes raw signals to check for duplicates which can definitely be improved. But yeah, didn't really think there was anything majorly wrong with my approach but i guess i will have to reconsider.


> Also why do you filled checklist for reviewer, if you are PR author, not the reviewer?

new to github, learning as i go

> Have you talked with IRDB maintainers about how you can do it properly? Because in current condition it looks like adding random remotes without verification, and its not good idea as I think.

not really, no. but would appreciate any help to get educated on this because yeah just trying to help out and don't want to cause more harm than help

**Review by skotopes — DISMISSED** [review]

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
@jaylikesbunda I've removed duplicates from [projector.ir](https://github.com/flipperdevices/flipperzero-firmware/pull/3929/commits/5948504cd88a3f7d5170b5811f156b3fab374e49).

**Comment by jaylikesbunda** [comment]
> @jaylikesbunda I've removed duplicates from [projector.ir](https://github.com/flipperdevices/flipperzero-firmware/pull/3929/commits/5948504cd88a3f7d5170b5811f156b3fab374e49).

thank you! i forgot about that one

**Pull request merged**
