### PR TITLE
Plantain parser improvements

### PR DESCRIPTION
**Pull request by assasinfil**
# What's new

- Added more parsed lines: validator, balance, tariff, trip time, count...

# Verification 

- Try to parse card and validate result with "Транспортные карты Москвы" or other parsing service.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by gornekich** [comment]
@assasinfil any news?

**Comment by assasinfil** [comment]
Im awating support from @rozetkinrobot. It's still in progress)

**Comment by gornekich** [comment]
@assasinfil any news?

**Comment by assasinfil** [comment]
> @assasinfil any news?

Awaiting rozetkin for support with parsing.

**Comment by assasinfil** [comment]
@gornekich I tested on community dumps, seems ok. Need additional testing (bsk, podoroznik).

**Review by Astrrra — APPROVED** [review]

**Comment by doomwastaken** [comment]
@Astrrra works fine on our plantain cards

**Review by skotopes — APPROVED** [review]

**Pull request merged**
