### PR TITLE
Add camera control mode to bluetooth remote app.

### PR DESCRIPTION
**Pull request by LoganMD**
# What's new

- Added a camera shutter remote to the bluetooth remote app for use with iOS/Android.

# Verification 

- Tested on Pixel 6 Pro & iPhone 11 Pro max.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by LoganMD** [comment]
Should pass all the checks now

**Comment by skotopes** [comment]
Why not to use media keyboard instead?

**Comment by LoganMD** [comment]
It's not well known that volume keys can control cameras, so having a dedicated camera mode helps

**Comment by LoganMD** [comment]
I'm improving the camera mode in the next commit, going to add a video mode & time elapsed for recording if possible

**Comment by skotopes** [comment]
@LoganMD ok, un-draft when ready.

**Comment by LoganMD** [comment]
Will do

**Comment by PseudoSwede16** [comment]
Very handy.
Thanks much!

**Pull request closed without merging**
