### PR TITLE
Remove execute permissions from *.c and *.h files

### PR DESCRIPTION
**Pull request by wdoekes**
# What's new

- `find . -type f -perm /111 -name '*.c' | xargs chmod 644`
- `find . -type f -perm /111 -name '*.h' | xargs chmod 644`

# Verification 

- Things still build and run.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
Doesn't make sense without enforcing tool.

**Review by skotopes — CHANGES_REQUESTED** [review]
Need some kinda of automation integrated with CI/CD.
Integration with `./fbt format` is the best option.

**Review by hedger — DISMISSED** [review]

**Comment by wdoekes** [comment]
FYI: My clang-format reports more issues in `lib/`:
```
lib/ST25RFAL002/source/rfal_st25xv.c:284:12: error: code should be clang-formatted [-Wclang-format-violations]
    msgIt =
           ^
lib/ST25RFAL002/source/rfal_st25xv.c:285:20: error: code should be clang-formatted [-Wclang-format-violations]
        (uint16_t)(msgLen + sizeof(flags) + sizeof(cmd) + 1U + ((uid != NULL) ? RFAL_NFCV_UID_LEN : 0U) + 1U + 1U);
                   ^
...
```
That explains why I missed the 755 on `rfal_nfc.c`.

```console
$ clang-format --version
clang-format version 10.0.0-4ubuntu1 

$ apt-cache policy clang-format | grep Installed
  Installed: 1:10.0-50~exp1
```

**Comment by skotopes** [comment]
@wdoekes We are planning to ship clang format with our toolchain soon. Till then you need to install specific version.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
