### PR TITLE
[FL-2976] SubGhz: add protocol "Ansonic"

### PR DESCRIPTION
**Pull request by Skorpionm**
# What's new

- SubGhz: add protocol "Ansonic"

# Verification 

- Compile and upload
- Run unit tests
- Check RX/TX

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by pbek** [comment]
Awesome! Thank you very much! I'll test it asap.

**Comment by pbek** [comment]
I tested the firmware and recorded the signal. It was detected correctly and yielded (for my dip-switch set):
[SCW Schranke PR.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9983085/SCW.Schranke.PR.sub.txt) (renamed to txt for github)

Other dip-switch configs were also detected correctly.
Thank you very much, @Skorpionm!

I'll test it with the boom.

**Comment by pbek** [comment]
Note: I didn't have my custom frequency any more, so I manually updated it to `434075000` in: 
[SCW Schranke PR adapted.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9983219/SCW.Schranke.PR.adapted.sub.txt)

**Comment by pbek** [comment]
I'm sorry to report that the boom didn't move with my two subs. 😬

**Comment by pbek** [comment]
@Skorpionm, will there be another build for your last commit?

**Comment by pbek** [comment]
Actually building yourself is dirt-easy. Respect!

**Comment by pbek** [comment]
The last commit still didn't open the boom. 
But I finally got one raw file to actually open the boom: 
[SCW Schranke x5 2m FM.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9995903/SCW.Schranke.x5.2m.FM.sub.txt)

**Comment by pbek** [comment]
Firmware worked (boom opened) with:

[SCW Schranke PR adapted.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/10014290/SCW.Schranke.PR.adapted.sub.txt)

**Comment by pbek** [comment]
I have built and tested the last commit and it (still) opened the boom! 👍🏻

**Comment by pbek** [comment]
Any chance of getting this merged? 😅

**Comment by skotopes** [comment]
@pbek you will not believe it but I'm currently working on this PR

**Comment by pbek** [comment]
Yay! That's awesome! 😁  Since building the firmware was made so amazingly easy using the PRs in the meantime was no problem. 😀

**Review by skotopes — APPROVED** [review]

**Comment by pbek** [comment]
Yay, thank you!

**Pull request merged**
