### PR TITLE
Skylanders plugin

### PR DESCRIPTION
**Pull request by bettse**
# What's new

- NFC Plugin to detect skylanders and show piece name (Need to add more from https://github.com/silicontrip/SkyReader/blob/master/toynames.cpp)

# Verification 

- Load [Chest.nfc.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13760047/Chest.nfc.txt) onto flipper
- Open NFC app
- Select Saved->Chest->Info
- See "Skylanders" and "Imaginite Mystery Chest" (name from https://skylanders.fandom.com/wiki/Imaginite_Mystery_Chests)

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by Ethanol0001** [comment]
This seems more than an app than a necessary plugin for the Flipper Zero. If you wish you can check out our Discord to see how to get started with making apps.

**Comment by bettse** [comment]
@Ethanol0001 That's sweet, but I'm Eric Betts.  I wrote [Seader](https://lab.flipper.net/apps/seader) and I'm co-author of the [Picopass](https://lab.flipper.net/apps/picopass) app.

**Comment by Ethanol0001** [comment]
Ok but that doesn’t mean we need a feature that barely anyone uses anymore that would be better fitted if published to the flipper app store instead.

**Comment by bettse** [comment]
1. There is almost 0 cost to a feature, even if almost no one uses it.
2. It clearly can be coded easily as a plugin, and requiring less work on my part than a full app
3. I think, even if no new versions are coming out, skylanders was popular enough that it is likely examples of NFC the average person could have.
4. There have been quite a few discussions about skylanders.  This person (https://github.com/V0lk3n/Flipper-Skylanders) even went so far as wanting to add their figure specific keys to the global key list back in the day 😁 .

**Comment by skotopes** [comment]
@bettse need help?

**Comment by bettse** [comment]
Screenshot-20240419-191458

Tested again

**Comment by gornekich** [comment]
Hi @bettse , thanks for PR!
Just want to confirm: all skylander tags has one password in 0 sector? There is no KDF?

**Comment by bettse** [comment]
> Just want to confirm: all skylander tags has one password in 0 sector? There is no KDF?

Sector 0 is always the same; the other sectors are using a KDF

**Comment by gornekich** [comment]
> Sector 0 is always the same; the other sectors are using a KDF

Is that KDF known?

**Comment by bettse** [comment]
> Is that KDF known?

yeah; it was published at https://nfc.toys/ and I think @noproto has worked on an implementation.  That could be added to this later

**Comment by gornekich** [comment]
> > Is that KDF known?
> 
> yeah; it was published at https://nfc.toys/ and I think @noproto has worked on an implementation. That could be added to this later

Got it, thanks!

**Review by gornekich — APPROVED** [review]

**Review by skotopes — APPROVED** [review]

**Pull request merged**
