### PR TITLE
fix: build on windows gives datetime format error

### PR DESCRIPTION
**Pull request by derskythe**
# What's new

- Fixed build on Windows #3195
- Tested on Windows and Debian

# Verification 

- `git clone`
- run `./fbt`

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by hedger** [comment]
That's odd, what's your setup - Windows, Git versions? System locale?

**Comment by derskythe** [comment]
> That's odd, what's your setup - Windows, Git versions? System locale?

Yes, I checked on the different system and can't reproduce.
But, different system has non-English locale.
So:

## Problem Windows 
- Version `10.0.19045 Build 19045`
- Git version: `2.42.0.windows.2`
- Locale: `en-US`
- `git log -1 --format=%cd` output: `Thu Nov 2 17:28:39 2023`

## Working Windows
- Version `10.0.19045 Build 19045`
- Git version: `2.41.0.windows.3`
- Locale: `ru-RU`
- `git log -1 --format=%cd` output: `Thu Nov 2 22:28:39 2023 +0900`

**Is the time zone of latest commit really that important when assembling?**

**Comment by derskythe** [comment]
Found difference, on the problem system `git config -e --global`:
```
[log]
   date = local
```

I can change my PR to check:
```bash
git config --get log.date
```

**Comment by hedger** [comment]
I'm not sure if it's feasible to support all possible date formats. I think it would be better to try parsing the most basic format (omitting the timezone) and, in other cases, throwing an error, suggesting the user to fix their git config.

**Comment by derskythe** [comment]
@hedger Agree, but I think some people don't want to calc local date of each committer and using this setting. 
This is not incorrect settings in git config. 
Why force these users to disable this setting just to compile the firmware?

**Comment by hedger** [comment]
There are other options for setting time format, `(relative|local|default|iso|iso-strict|rfc|short|raw)`. Luckily, `git log` can override the effective time format - no need to check for whatever user has set there.

So, you can just add `--date=default` to `git log` args and leave other parts as they are.

**Comment by derskythe** [comment]
Create PR #3202, this PR is dirty

**Pull request closed without merging**
