### PR TITLE
NFC: fix MFC timings

### LINKED ISSUE #2718: Emulation timing regression after PR #2070
### Describe the bug.

After merging PR #2070 frame delay time increased in 50%

In both cases Flipper has Debug: Off and Log Level: Default

### Reproduction

1. Emulate MFC on Flipper Zero
2. Read sector or block with proxmark3 (hf mf rdsc -s 0 -k FFFFFFFFFFFF)
3. Check frame times (hf mf list --frame)
4. Revert commit e1c6e78b2ecdfe6da19c04d4e16b95c7f8247e9f and try again

### Target

_No response_

### Logs

```Text
Trace before:

      Start |        End | Src | Data (! denotes parity error)                                           | CRC | Annotation
------------+------------+-----+-------------------------------------------------------------------------+-----+--------------------
          0 |        992 | Rdr |52(7)                                                                    |     | WUPA
        992 |       2116 |     |fdt (Frame Delay Time): 1124
       2116 |       4484 | Tag |44  00                                                                   |     | 
       7040 |       9504 | Rdr |93  20                                                                   |     | ANTICOLL
       9504 |      10564 |     |fdt (Frame Delay Time): 1060
      10564 |      16452 | Tag |04  d3  c7  60  70                                                       |     | 
      19072 |      29600 | Rdr |93  70  04  d3  c7  60  70  74  b9                                       |  ok | SELECT_UID
      29600 |      30660 |     |fdt (Frame Delay Time): 1060
      30660 |      34180 | Tag |08  b6  dd                                                               |     | 
      36352 |      41056 | Rdr |60  00  f5  7b                                                           |  ok | AUTH-A(0)
      41056 |      47060 |     |fdt (Frame Delay Time): 6004
      47060 |      51796 | Tag |71  97  f8  ce                                                           |     | AUTH: nt 
      61184 |      70560 | Rdr |f2  2e  53! f5  cf  cc! 10  37                                           |     | AUTH: nr ar (enc)
      70560 |      78660 |     |fdt (Frame Delay Time): 8100
      78660 |      83396 | Tag |51! b4  e0  9f!                                                          |     | AUTH: at (enc)
      89344 |      94112 | Rdr |33  70! ae  fc!                                                          |     | 
            |            |  *  |                                              key FFFFFFFFFFFF prng HARD |     |
            |            |  *  |30  00  02  A8                                                           |  ok | READBLOCK(0)
      94112 |     113124 |     |fdt (Frame Delay Time): 19012
     113124 |     133988 | Tag |e8! fb! d4  e1  50  b3  6c  3e  06  d1  67! eb! 0a! 6a  d9! e9! 3b  69!  |     | 
            |            |  *  |04  D3  C7  60  70  08  44  00  FF  FF  FF  FF  FF  FF  FF  FF  EF  6F   |  ok | 
     147200 |     151968 | Rdr |c3  17! 93! 0c!                                                          |     | 
            |            |  *  |30  01  8B  B9                                                           |  ok | READBLOCK(1)
     151968 |     170884 |     |fdt (Frame Delay Time): 18916
     170884 |     191684 | Tag |cb! a5! de  95! 74! 98  12! c4  78! 32  6c! f8  e2! b4  d7  f5! c0! 51!  |     | 
            |            |  *  |FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  37  CB   |  ok | 
     204928 |     209632 | Rdr |13! 6a  51  ab!                                                          |     | 
            |            |  *  |30  02  10  8B                                                           |  ok | READBLOCK(2)
     209632 |     228564 |     |fdt (Frame Delay Time): 18932
     228564 |     249428 | Tag |cb  78! 90  e5! 87! f0  81! a2! b7! 0e  a0  7b  d3  f4! 3b  d2  2d  c6!  |     | 
            |            |  *  |FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  37  CB   |  ok | 
     262528 |     267232 | Rdr |5c  7b! 22! 0b!                                                          |     | 
            |            |  *  |30  03  99  9A                                                           |  ok | READBLOCK(3)
     267232 |     286308 |     |fdt (Frame Delay Time): 19076
     286308 |     307172 | Tag |60! 23! f0! 6b  a7! 88! 12! a6  8b! 8b  bf  fc  c9! 32! 1f! 83  9f! 70   |     | 
            |            |  *  |00  00  00  00  00  00  FF  07  80  69  FF  FF  FF  FF  FF  FF  D4  55   |  ok | 
     320256 |     325024 | Rdr |1b! 8b! 7a! 14!                                                          |     | 
            |            |  *  |50  00  57  CD                                                           |  ok | HALT

After:

      Start |        End | Src | Data (! denotes parity error)                                           | CRC | Annotation
------------+------------+-----+-------------------------------------------------------------------------+-----+--------------------
          0 |        992 | Rdr |52(7)                                                                    |     | WUPA
        992 |       2116 |     |fdt (Frame Delay Time): 1124
       2116 |       4484 | Tag |44  00                                                                   |     | 
       7040 |       9504 | Rdr |93  20                                                                   |     | ANTICOLL
       9504 |      10564 |     |fdt (Frame Delay Time): 1060
      10564 |      16452 | Tag |04  e2  ff  09  10                                                       |     | 
      19072 |      29536 | Rdr |93  70  04  e2  ff  09  10  1a  78                                       |  ok | SELECT_UID
      29536 |      30660 |     |fdt (Frame Delay Time): 1124
      30660 |      34180 | Tag |08  b6  dd                                                               |     | 
      36352 |      41056 | Rdr |60  00  f5  7b                                                           |  ok | AUTH-A(0)
      41056 |      49348 |     |fdt (Frame Delay Time): 8292
      49348 |      54020 | Tag |df  de  45  96                                                           |     | AUTH: nt 
      63488 |      72800 | Rdr |9c  3b! 0b! b5! 9a  40  cf  31!                                          |     | AUTH: nr ar (enc)
      72800 |      83284 |     |fdt (Frame Delay Time): 10484
      83284 |      87956 | Tag |f9! 58  9d  37!                                                          |     | AUTH: at (enc)
      93952 |      98720 | Rdr |24  5c! 37! e9                                                           |     | 
            |            |  *  |                                              key FFFFFFFFFFFF prng HARD |     |
            |            |  *  |30  00  02  A8                                                           |  ok | READBLOCK(0)
      98720 |     127892 |     |fdt (Frame Delay Time): 29172
     127892 |     148692 | Tag |f8  c4  68  32  55! 3c! f4  5b  98! 5d  34! ab  34! 63! 4e! 08! 2f! 80!  |     | 
            |            |  *  |04  E2  FF  09  10  08  44  00  FF  FF  FF  FF  FF  FF  FF  FF  17  D6   |  ok | 
     161920 |     166688 | Rdr |33! 9e  33  bb!                                                          |     | 
            |            |  *  |30  01  8B  B9                                                           |  ok | READBLOCK(1)
     166688 |     195876 |     |fdt (Frame Delay Time): 29188
     195876 |     216740 | Tag |e7  97! 37! 53  81  e7  77  11  d3  20  98! ab  80  58! f1! 05  5b! 1e!  |     | 
            |            |  *  |FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  37  CB   |  ok | 
     229888 |     234592 | Rdr |d0! 0c  a9  7e                                                           |     | 
            |            |  *  |30  02  10  8B                                                           |  ok | READBLOCK(2)
     234592 |     263844 |     |fdt (Frame Delay Time): 29252
     263844 |     284708 | Tag |29  92! 1d  25! 13! e9! a9  f1! 33  9d! 11! c2! 09  95  7b  83  84  42!  |     | 
            |            |  *  |FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  37  CB   |  ok | 
     297856 |     302560 | Rdr |68! 39  af  02!                                                          |     | 
            |            |  *  |30  03  99  9A                                                           |  ok | READBLOCK(3)
     302560 |     331796 |     |fdt (Frame Delay Time): 29236
     331796 |     352660 | Tag |3a  d6  3f! d9! 1c! cc! 50  c5  e9! ae  c6  9f! a8! d5! 4b  fd! 70  c0!  |     | 
            |            |  *  |00  00  00  00  00  00  FF  07  80  69  FF  FF  FF  FF  FF  FF  D4  55   |  ok | 
     365696 |     370400 | Rdr |d5! d2  0b  fb!                                                          |     | 
            |            |  *  |50  00  57  CD                                                           |  ok | HALT
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by gornekich**
# What's new

- Optimize DigitalSignal lib to improve MFC emulation
- Build DigitalSignal as separate library
- Improve unit tests
- Fixes #2718 

# Verification 

- During MFC emulation Nt response fits in 500us timeout
- Confirm NFC unit tests don't fail

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by AloneLiberty** [comment]
Tried to add more optimization parameters, was able to decrease from ~22200 to ~21600, of course this is not much, but better that nothing (especially with zero code changes).

I don't know exactly which of them helped (I just set all that I know):
```O3,unroll-loops,Ofast,loop-interchange,inline-functions-called-once,tree-vectorize,align-functions,align-labels,align-loops,align-jumps```

Maybe some of them are worth adding?

**Comment by gornekich** [comment]
@AloneLiberty Unfortunately I don't have readers that can't read Flipper MFC emulation. I think problem here is that some readers wait no longer than 500us for nt message from tags. We perform these optimization to fit 500us timeout, however in MFC documentation the timeout for this message is 1ms.

I think we should stop optimizing for now, merge this PR and gather feedback from users who experienced emulation regression. If it's not enough, we will continue

**Comment by g3gg0** [comment]
Just got pointed here. Will look into it.
The DigitalSequence was introduced to reduce the huge delay (or memory consumption) i had when implementing ISO15693 modulation.

**Comment by gornekich** [comment]
Hi @g3gg0 
Consider this PR as a quick fix. I added some compile-time optimization and removed this line
`uint32_t edge_scaled = (internals->factor * signal->edge_timings[pos]) / (1024 * 1024);`

I understand the idea of internal->factor, but I don't see where it is set different from (1024 * 1024). I see that in #2316 internal->factor = (1024 * 1024) as well. Since multiplying and dividing on the same value is useless and takes CPU time, I removed it. 

Did you use it only for debugging?

**Review by skotopes — APPROVED** [review]

**Comment by g3gg0** [comment]
this 1024/1024 is a service provided by 
``` void digital_sequence_timebase_correction(DigitalSequence* sequence, float factor); ```
allowing the scaling of signals to match an exact frequency if needed.

so yes, this is not necessary, then you can also remove the function as well.

**Comment by g3gg0** [comment]
@gornekich 
https://github.com/g3gg0/flipperzero-firmware/tree/ISO14443_digital_sequence
I have a branch here that makes use of DigitalSequence (which had to be optimized further)

what are your thoughts on that?
grafik
grafik

also i have seen @skotopes dealing with bus enable/disable stuff.
[here i had to disable ](https://github.com/g3gg0/flipperzero-firmware/blob/ed2c8f8167e706c95e22b91e189ce643a2e82be0/lib/digital_signal/digital_signal.c#L256) dis/enabling FuriHalBusTIM2 else i got a lock up after a few messages.
not sure why this happens. any ideas?

grafik

edit:
solved. was a special condition when the bus was disabled without enabling before.
thanks for that check :)

**Comment by g3gg0** [comment]
updated the repo, looks quite stable now.

**Pull request merged**
