### PR TITLE
NFC: Fix gen1 writing with invalid BCC (lost fix from PR #2511)

### PR DESCRIPTION
**Pull request by AloneLiberty**
# What's new

- Returned the lost fix from PR #2511 

# Verification 

From old PR:

- Try writing gen1a tag with invalid BCC (not readable via Flipper NFC app, but visible in 'Check Magic tag'). Tag should be writable.
- Try writing gen1a tag with valid BCC. Tag also should be writable.
- Try writing non gen1a tag. App should show that the card isn't magic.

New:

- Try writing gen4 tag

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by hedger** [comment]
;D

**Comment by skotopes** [comment]
Couple notes:
- write for me is broken, all attempts ends with "not all sectors were written correctly"
- wipe fails on random blocks

**Comment by skotopes** [comment]
Same issues with gen1.
@Astrrra @gornekich this one requires help from your side and full set of tests.

**Comment by AloneLiberty** [comment]
Can you please try again on updated sources? It should work now

**Comment by skotopes** [comment]
- Gen1 wipe works
- Gen1 write works
- Gen4 wipe fails
- Gen4 write fails

Card is alive, old firmware and proxmark can write it without any issue

**Comment by AloneLiberty** [comment]
I'm unsure what can cause this issues, maybe this will fix it
With last commit I can assume:
 - I didn't touched any detection code
 - I didn't touched anything in wipe for gen4

**Comment by AloneLiberty** [comment]
Tested on mine gen2 super card (gen4 chip), should work now (write/wipe)

**Comment by skotopes** [comment]
Please avoid force pushes into active branches, it makes difficult to track changes for us

**Comment by skotopes** [comment]
Writing/wiping gen4 is fixed

**Comment by skotopes** [comment]
We'll wait for approval from one more person and then we can merge this PR

**Review by skotopes — APPROVED** [review]

**Pull request merged**
