### PR TITLE
UPC-A barcode generator

### PR DESCRIPTION
**Pull request by Kavitate**
# What's new

- The readme file needs updated as the current image shows the old naming of "UPC Generator" where it should show the new "Barcode Generator" name similar to the image I have attached.

# Verification 

- Verified the name change consistent with the new RogueMaster version 0.64.5-0817-RM.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

Menu

### CODE REVIEW

**Comment by RogueMaster** [comment]
Did you post this here in error? Your application.fam doesn't have your desired naming according to PR notes.

**Comment by RogueMaster** [comment]
Also, @McAzzaMan would need to permit for this to be pushed to main

**Comment by Kavitate** [comment]
I only wanted to update the readme file to reflect the updated image. I am unsure why it has pulled everything else under it. The changes described above are the only thing I am wanting to update. The "9 commits" it has tacked in with it are irrelevant to what I am trying to accomplish. If that makes sense?

**Comment by RogueMaster** [comment]
It as a PR on the main github instead of to your own still doesn't make sense.

**Comment by Kavitate** [comment]
I think it defaulted to that and I must not have seen it. All I am trying to do is update the first image on the below link to the image I have uploaded above in order to make the documentation more accurate.

https://github.com/McAzzaMan/flipperzero-firmware/blob/UPC-A_Barcode_Generator/applications/barcode_generator/readme.md

**Comment by Kavitate** [comment]
I believe I have found the correct way to do this so I will close this request. Thank you for your time.

**Pull request closed without merging**
