### PR TITLE
Update subghz_cli.c M_STR1NG variables

### PR DESCRIPTION
**Pull request by RogueMaster**
Seems like this file requires these silly updates

# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
Hi. What is it? Can we have description for this PR?
Also M_STR1NG_UTF8_STARTING is not defined anywhere. Are you sure that your submodules are ok?

**Comment by RogueMaster** [comment]
If you update submodules for mlib, a compile error will arise... see mlib file here for where it gets defined... 

https://github.com/P-p-H-d/mlib/blob/master/m-string.h#L67

**Comment by RogueMaster** [comment]
I used: git submodule update --init --recursive --remote

**Comment by skotopes** [comment]
You are referencing master branch, but we use release version:

https://github.com/P-p-H-d/mlib/blob/62c8ac3e5d4a7a4f8757328e7a80286fde2686b6/m-string.h

Which doesn't have this variable, please ensure that your submodule properly initialised and uses correct version (62c8ac3e5d4a7a4f8757328e7a80286fde2686b6)

**Pull request closed without merging**
