### PR TITLE
[FL-2554] Embedded arm-none-eabi toolchain

### PR DESCRIPTION
**Pull request by drunkbatya**
# What's new

Embedded arm-none-eabi toolchain, with all accompanying tools needed by FBT:
- [FL-2554](https://flipperzero.atlassian.net/browse/FL-2554) - Linux x86_64
- [FL-2587](https://flipperzero.atlassian.net/browse/FL-2587) - Windows i686
- [FL-2617](https://flipperzero.atlassian.net/browse/FL-2617) - MacOS x86_64 (M1 with Rosetta)

# Verification 

Run ./fbt on pure Linux, MacOS and Windows systems, no addition tools required, except git. All targets like flash, debug etc. should work.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by RogueMaster** [comment]
You may want to add chmod 744 scripts/toolchain/unix-toolchain-download.sh to download_toolchain() to avoid a permissions error. When adapting the changes, I got that error initially.

**Comment by RogueMaster** [comment]
Tested on a fresh Debian 11.3 build.
**The only commands entered for this fresh install were:**

> su -
> apt update
> apt install vim git python docker docker-compose openocd dfu-util python3-protobuf protobuf-compiler
> mkdir /root/flipper
> cd /root/flipper
> git clone --recursive https://github.com/RogueMaster/flipperzero-firmware-wPlugins.git
> cd flipperzero-firmware-wPlugins
> docker-compose up -d
> chmod 744 scripts/toolchain/unix-toolchain-download.sh
> docker-compose exec dev ./fbt

Got this error on compile:

	PROTO	assets/protobuf/application.proto

         *************************************************************
         *** Could not import the Google protobuf Python libraries ***
         *** Try installing package 'python3-protobuf' or similar.  ***
         *************************************************************
    
Traceback (most recent call last):
  File "/project/lib/nanopb/generator/nanopb_generator.py", line 36, in <module>
    import google.protobuf.text_format as text_format
  File "/project/toolchain/x86_64-linux/python/lib/python3.9/site-packages/google/protobuf/text_format.py", line 53, in <module>
    from google.protobuf.internal import type_checkers
  File "/project/toolchain/x86_64-linux/python/lib/python3.9/site-packages/google/protobuf/internal/type_checkers.py", line 48, in <module>
    import ctypes
  File "/project/toolchain/x86_64-linux/python/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
scons: *** [build/f7-firmware-C/assets/compiled/application.pb.c] Error 1
********** ERRORS **********
Failed building build/f7-firmware-C/assets/compiled/application.pb.c: Error 1

**Comment by djsime1** [comment]
👍 Successfully compiled and flashed (Via USB) on native Windows 10. I don't have an ST-LINK to test other modes.

**Comment by RogueMaster** [comment]
> Tested on a fresh Debian 11.3 build. **The only commands entered for this fresh install were:**
> 
> > su -
> > apt update
> > apt install vim git python docker docker-compose openocd dfu-util python3-protobuf protobuf-compiler
> > mkdir /root/flipper
> > cd /root/flipper
> > git clone --recursive https://github.com/RogueMaster/flipperzero-firmware-wPlugins.git
> > cd flipperzero-firmware-wPlugins
> > docker-compose up -d
> > chmod 744 scripts/toolchain/unix-toolchain-download.sh
> > docker-compose exec dev ./fbt
> 
> Got this error on compile:
> 
> ```
> PROTO	assets/protobuf/application.proto
> 
>      *************************************************************
>      *** Could not import the Google protobuf Python libraries ***
>      *** Try installing package 'python3-protobuf' or similar.  ***
>      *************************************************************
> ```
> 
> Traceback (most recent call last): File "/project/lib/nanopb/generator/nanopb_generator.py", line 36, in import google.protobuf.text_format as text_format File "/project/toolchain/x86_64-linux/python/lib/python3.9/site-packages/google/protobuf/text_format.py", line 53, in from google.protobuf.internal import type_checkers File "/project/toolchain/x86_64-linux/python/lib/python3.9/site-packages/google/protobuf/internal/type_checkers.py", line 48, in import ctypes File "/project/toolchain/x86_64-linux/python/lib/python3.9/ctypes/**init**.py", line 8, in from _ctypes import Union, Structure, Array ImportError: libffi.so.7: cannot open shared object file: No such file or directory scons: *** [build/f7-firmware-C/assets/compiled/application.pb.c] Error 1 ********** ERRORS ********** Failed building build/f7-firmware-C/assets/compiled/application.pb.c: Error 1

Seems like this issue I was having happens with all builds on this new install... have tried uninstalling and reinstalling protobuf and nanopb several times

**Comment by RogueMaster** [comment]
Actually those errors may be related after all. My build will work without those changes and then fail to compile anew with them

**Comment by drunkbatya** [comment]
We are added some fixes to toolchain, please redownload it by mannual removing [repo root]/toolchain dir and starting ./fbt again.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
