### PR TITLE
[FL-2904, FL-2900, FL-2890] WS: add  app WeatherStation

### PR DESCRIPTION
**Pull request by Skorpionm**
# What's new

- [FL-2904] WS: add  app WeatherStation
- WS: add inFactory-TH protocol
- WS: add protocol ThermoPRO_TX4
- [FL-2900] SubGhz: Move icons in Sub-GHz
- [FL-2890] SubGhz: Rename *_user files in resources to _user.example
- WS: add protocol Nexus-TH

# Verification 

- run the application and check if it works

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

[FL-2904]: https://flipperzero.atlassian.net/browse/FL-2904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FL-2900]: https://flipperzero.atlassian.net/browse/FL-2900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FL-2890]: https://flipperzero.atlassian.net/browse/FL-2890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by digitalcircuit** [comment]
Thank you for taking this up!

If you feel up to [implementing the protocol used by the WT2022A/etc sensors (temperature, humidity, low battery indication)](https://forum.flipperzero.one/t/new-protocol-433-92-mhz-am270-wittime-wt2022a-wireless-hygro-thermometer-3-channel/4018/1 ), I'd be happy to help test the WeatherStation reception whenever you're ready.  Since I made that post, I now have three  active WT2022A sensors set up to broadcast on all 3 selectable channels (1, 2, and 3).

**Comment by Skorpionm** [comment]
> Спасибо, что взялись за это!
> 
> Если вы готовы [реализовать протокол, используемый датчиками WT2022A/и т. д. (температура, влажность, индикация низкого заряда батареи)](https://forum.flipperzero.one/t/new-protocol-433-92-mhz-am270-wittime-wt2022a-wireless-hygro-thermometer-3-channel/4018/1) , я буду рад помочь протестировать прием WeatherStation, когда вы будете готовы. С тех пор, как я сделал этот пост, у меня теперь есть три активных датчика WT2022A, настроенных для вещания на всех трех выбираемых каналах (1, 2 и 3).
answered on the forum

**Comment by digitalcircuit** [comment]
As [shared on the Flipper Zero forums (including a photo for the curious)](https://forum.flipperzero.one/t/new-protocol-433-92-mhz-am270-wittime-wt2022a-wireless-hygro-thermometer-3-channel/4018/17 ), this works with all three wireless sensors for my weather station. :+1:

**Review by skotopes — APPROVED** [review]

**Comment by igorek2404** [comment]
Please can add my weather station Oregon2
image

**Comment by skotopes** [comment]
@igorek2404 fixed in dev, will be included in next release. Thanks to @Shmuma for #1910

**Pull request merged**
