### PR TITLE
delete extra spaces, grammar fixes

### PR DESCRIPTION
**Pull request by crunchypeanutbutter1**
# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by hedger** [comment]
What's the point?

**Comment by crunchypeanutbutter1** [comment]
> 

grammar fix, has no real point to be honest, accepted the challenge to get the most minor edit to get a contributor role, just thought a special role on Discord would be fun

**Comment by AloneLiberty** [comment]
Path is `Path` on purpose, not a typo:
```
>>> from pathlib import path
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'path' from 'pathlib' (/usr/lib/python3.11/pathlib.py)
>>> from pathlib import Path
>>>
```

**Comment by crunchypeanutbutter1** [comment]
yup I'm dumb! definitely wasn't paying attention and for some reason thought it was commented out

**Pull request closed without merging**
