### PR TITLE
Frequency analyzer: allow setting rssi threshold

### PR DESCRIPTION
**Pull request by iRonJ**
# What's new

On the frequency analyzer, you can set the RSSI threshold that the UI will show a detected frequency.
image

# Verification 

Launch the Sub-Ghz frequency analyzer, and press the up/down buttons to change the threshold. Lowering the threshold will allow signals that are weaker to be shown as detected, and logged if they meet the appropriate criteria for logging (unchanged).

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by Skorpionm** [comment]
sorry, but what is it for?

**Comment by iRonJ** [comment]
> sorry, but what is it for?

If you want to only see signals that are very strong, or if you want to see what weaker signals are around, you can adjust the level the frequency analyzer triggers at.

**Comment by Skorpionm** [comment]
no need to unscrew rssi below the set threshold in the official firmware.  and everything will work as it should

**Comment by skotopes** [comment]
@iRonJ I think what @Skorpionm is trying to say is "is it working? Is it working in meaningful way?"

One important things is: antenna is being disconnected when you use Frequency Analyzer, so there is not so much of the signal. Lowering trigger RSSI doesn't make much sense because it comes too close to the noise floor.

If you want to catch weak signal you need to connect antenna first. But if you'll do that you'll start to receive a lot of different signals from around you and distinguishing your signal from the others will be quite complex.

Implementing it right will require some work:
- Use antenna in FA
- Dynamically calculate and subtract environment spectrum
- Tune chip RF params 
- And a lot of experiments to fine tune it

**Comment by iRonJ** [comment]
> @iRonJ I think what @Skorpionm is trying to say is "is it working? Is it working in meaningful way?"
> 
> One important things is: antenna is being disconnected when you use Frequency Analyzer, so there is not so much of the signal. Lowering trigger RSSI doesn't make much sense because it comes too close to the noise floor.
> 
> If you want to catch weak signal you need to connect antenna first. But if you'll do that you'll start to receive a lot of different signals from around you and distinguishing your signal from the others will be quite complex.
> 
> Implementing it right will require some work:
> 
> * Use antenna in FA
> * Dynamically calculate and subtract environment spectrum
> * Tune chip RF params
> * And a lot of experiments to fine tune it

That is good information I didn’t know. My use case was trying to determine if a zigbee radio was operating subghz. I wasn’t getting any triggering with stock fw. Lowering the threshold let me confirm the zigbee radio was likely operating at the higher carrier and that it wasn’t some other error in the detection.

**Comment by iRonJ** [comment]
> > @iRonJ I think what @Skorpionm is trying to say is "is it working? Is it working in meaningful way?"
> > One important things is: antenna is being disconnected when you use Frequency Analyzer, so there is not so much of the signal. Lowering trigger RSSI doesn't make much sense because it comes too close to the noise floor.
> > If you want to catch weak signal you need to connect antenna first. But if you'll do that you'll start to receive a lot of different signals from around you and distinguishing your signal from the others will be quite complex.
> > Implementing it right will require some work:
> > 
> > * Use antenna in FA
> > * Dynamically calculate and subtract environment spectrum
> > * Tune chip RF params
> > * And a lot of experiments to fine tune it
> 
> That is good information I didn’t know. My use case was trying to determine if a zigbee radio was operating subghz. I wasn’t getting any triggering with stock fw. Lowering the threshold let me confirm the zigbee radio was likely operating at the higher carrier and that it wasn’t some other error in the detection.

What if the UI wasn’t visible by default, and then only if the user pressed up or down the value showed up, as an additional diagnostic?

**Pull request closed without merging**
