### PR TITLE
Add function keys for hid keyboard

### PR DESCRIPTION
**Pull request by L4ys**
# What's new

- Add function keys to keyboard of HID app, ported from original implementation: https://github.com/huuck/FlipperZeroUSBKeyboard

# Verification 
- There should be a new row with function keys below the Ctrl / Alt keys
image

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by hramrach** [comment]
The keyboard screen is already full, and has number keys.

Maybe you could add a FN in addition to shift to enable other functions, such as turning number keys into function keys.

**Comment by skotopes** [comment]
Hi. This PR is currently waiting for UX team, scheduled for next release.

**Comment by OperKH** [comment]
Original implementation also have Esc key. Would be nice to add it to.

**Comment by skotopes** [comment]
#2362 better nailed buttons, I'll merge it instead

**Pull request closed without merging**
