### PR TITLE
Ok to cycle animation

### PR DESCRIPTION
**Pull request by itsweekly**
# What's new

- Hold Ok to cycle to another animation
- Quality of life feature 

# Note
- Has been done before
- 
# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
;-) Nope

**Comment by RaZeSloth** [comment]
> ;-) Nope

Why not tho? Seems like a fun feature.

**Comment by itsweekly** [comment]
> > ;-) Nope
> 
> Why not tho? Seems like a fun feature.

Yeah

**Comment by skotopes** [comment]
@itsweekly @RaZeSloth this feature was explicitly designed in that way. Something that is not under your control. This PR just breaks whole thing.

**Comment by itsweekly** [comment]
> @itsweekly @RaZeSloth this feature was explicitly designed in that way. Something that is not under your control. This PR just breaks whole thing.

I don't really get what you mean, if it was designed that way then I understand, but I have tested this

**Pull request closed without merging**
