### PR TITLE
Electra lfrfid protocol implementation

### PR DESCRIPTION
**Pull request by Leptopt1los**
# What's new

Electra intercom (Romania) lfrfid protocol implementation
Solves https://github.com/flipperdevices/flipperzero-firmware/issues/1500 and https://forum.flipper.net/t/electra-intercom/6368

# Verification 

- Write to t5577 random em4100
- to blocks 3-4 write 0x7E71AAAA 0xAAAAAAAA
- set maxblck to 4
OR
- Go to lfrfid -> extra actions -> add manually -> Electra Group Electra
- Fill with random data, but set last 3 bytes as 7E 71 AA
- Save the dump, write to t5577
OR
- Get original Electra intercom tag
OR
- Use ask raw dump emulation on another flipper zero

AND read the tag. Must be detected as Electra Group Electra

After this:
- Test reading, writing to t5577 and emulation (read with pm3/another flipper zero)
- Test regression on EM4100 tags

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by DrZlo13 — APPROVED** [review]
The code works, no regressions, but I don't have the original Electra cards.
It also appears that proxmark does not know this protocol.

Anyway, good job, I think this is a good place to start.

**Comment by bogzik** [comment]
Can you be more explicit regarding the description of all the steps for implementing Electra Intercom in lfrid protocol? Thank you!

**Comment by d3xt3r01** [comment]
@skotopes Works. I found a small issue. On latest dev now. After a power off/on the info shows epilogue as 00000000... After an emulation info shows the correct epilogue again.

**Comment by skotopes** [comment]
@Leptopt1los wanna add fix to this RC? or next one?)

**Comment by Leptopt1los** [comment]
@skotopes can fix it tomorrow. just need to trigger ‎protocol_electra_encoder_start in render method before printf. or print epilogue directly from decoded data (a faster, but smellier solution)

**Pull request merged**
