### PR TITLE
Improved Snake with Notification and Score

### PR DESCRIPTION
**Pull request by RogueMaster**
# What's new

- updated snake to have notifications on capture and a score on the top right. 

# Verification 

- open snake and play to capture 

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by Astrrra** [comment]
Again, please fill the description and verification fields

**Comment by RogueMaster** [comment]
> Again, please fill the description and verification fields

My apologies, the comments have been updated.

**Comment by RogueMaster** [comment]
@whoamins hope you don't mind the inspiration from your code for the score shown and @MuddledBox for the notification

**Review by whoamins — DISMISSED** [review]

**Comment by RogueMaster** [comment]
Many changes provided on the last update by @xMasterX

**Comment by xMasterX** [comment]
> Many changes provided on the last update by @xMasterX

Hi,
I did not asked you to add my changes to this PR, I made them for my fork, not for someone push them into official PR without even asking me, 
if I wanted them to be in official firmware, I could just create PR by myself

**Comment by skotopes** [comment]
@xMasterX I'm closing this PR then.

**Pull request closed without merging**
