### PR TITLE
 Assets: correct MicroSD card pinout in icons

### PR DESCRIPTION
**Pull request by DXVVAY**
# What's new

- [ Missed SD card animations for correcting SD card pinout]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by DXVVAY** [comment]
@skotopes there made a new pr

**Comment by skotopes** [comment]
image

PRs that can not be synchronized with our dev will be closed.

**Comment by DXVVAY** [comment]
> image
> 
> PRs that can not be synchronized with our dev will be closed.

How do i fix it then

**Comment by skotopes** [comment]
@DXVVAY normally it's controlled by options when you create new PR and your fork visibility settings.

To bo honest I never were able to produce this issue with my own repositories.
There were couple people with this issue before and they solved it by them self.

**Comment by DXVVAY** [comment]
> @DXVVAY normally it's controlled by options when you create new PR and your fork visibility settings.
> 
> To be honest I've never were able to produce this issue with my own repositories. There were couple people with this issue before and they solved it by them self.

maybe it wasnt up to date?

**Comment by skotopes** [comment]
Yes, it was not up to date. And it was not allowing us to update it.
That makes whole process extremely difficult: basically we have wait for PR creator to sync his branch before we were able to merge it, which is not an option when we merge a lot of pull requests at the same time.

**Comment by DXVVAY** [comment]
> Yes, it was not up to date. And it was not allowing us to update it. That makes whole process extremely difficult: basically we have wait for PR creator to sync his branch before we were able to merge it, which is not an option when we merge a lot of pull requests at the same time.

So, if i make a new pr and keep it up to date it should be possible?

**Pull request closed without merging**
