### PR TITLE
Furi: Add "out of memory" and "malloc(0)" crash messages

### PR DESCRIPTION
**Pull request by WillyJL**
# What's new

- Clear crash messages for "out of memory" and "malloc(0)"
- Allows for easier debugging of what went wrong

# Verification 

- Crash by out of memory or malloc(0), see new messages

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
`malloc(0)` should be valid AFAIK, so maybe it's better to skip the check (and `memset`) in that case.

**Comment by WillyJL** [comment]
Usually, from my experience, malloc(0) indicates that some unexpected input was given to something that wasn't made to support it, so it would expect to always get back a pointer from malloc and use it anyway. Giving back NULL I imagine would cause follow up issues, which would make it even more difficult to track down... perhaps we could do as I suggested on the discord contributor channel, make a second mallow_notrow() or similar, that doesn't check the return?

Also I see that memmgr is being reworked in a PR recently, so might be best to wait for that

**Comment by CookiePLMonster** [comment]
> make a second mallow_notrow() or similar, that doesn't check the return?

That would be nice - and then `operator new()` could be mapped to `malloc`, as it most likely is already, while `operator new(std::nothrow)` - to `malloc_nothrow`. I'm not sure if this one is defined when exceptions are disabled, though.

**Comment by skotopes** [comment]
@CookiePLMonster embed makes following standards too dangerous. So we intentionally make them much stricter, that allows us to crash early.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
