### PR TITLE
Dolphin Backup / Restorer

### PR DESCRIPTION
**Pull request by RogueMaster**
# What's new
Not sure if this clone is wanted, but I added a Storage Move To SD clone to restore Dolphin Internal Files from SD to Internal. Also modified Storage Move To SD so it backs up Dolphin Internal Files from Internal to /ext/dolphin_restorer

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by DoberBit** [comment]
You just destroyed recent work from one of firmware developers
PR #1384

**Comment by RogueMaster** [comment]
> You just destroyed recent work from one of firmware developers PR #1384

Nobody asked you and I improved upon it. It was requested to put in separate PR, or can't you read?

**Comment by Astrrra** [comment]
This is an official warning. Please, keep discussions here civilized and **respect other users**.  


Also, **please** consult with us before working on a PR, as most of our software design decisions (including this one)  have a reason why they're done this way, and we won't be able to merge a PR that contradicts it.

**Comment by RogueMaster** [comment]
> this way

Hi Astrrra, can you please advise how this is contradicting something done a certain "way"? Are any changes needed?

**Comment by RogueMaster** [comment]
> please consult with us before working on a PR

My own PR was requested in #1384

**Comment by RogueMaster** [comment]
> My own PR was requested in #1384

Not that I expect it to be accepted without possible changes but I am following directions to contribute a very useful feature

**Comment by RogueMaster** [comment]
@nminaylov I used your work in this PR, I hope you don't mind. I am very glad you posted this code.

**Comment by RogueMaster** [comment]
Refactored for future merge

**Comment by RogueMaster** [comment]
The benefits of backing up and restoring from SD are obvious. Is this something that is wanted on the main FW?

Due to changes in the code, and the fact that I don't know how to make the new changes work with the changes desired for this PR, the storage_move_to_sd.c in this PR seems to still work similar to as desired but also accomplishes the backup of internal files as needed for the PR.

If this will not be desired, I can close.

**Comment by RogueMaster** [comment]
Since the moderators of this community don't enforce GPL restrictions on other members and moderators changing the licensing of an open source submission, I am withdrawing my Pull Request. GPL is made the way it is to avoid these problems. The moderators of the community are actively hindering the evolution of the project by going against GPL. Don't pretend to support open source and then go against it. Buyers beware!

**Pull request closed without merging**
