### PR TITLE
Add an NFC parser for the San Francisco Bay Area "Clipper" transit card.

### PR DESCRIPTION
**Pull request by ke6jjj**
# What's new

This is a parser/formatter for the "Clipper" NFC transit card, which is a Mifare DESFire application used in the San Francisco Bay Area. It currently decodes the following fields:

* Device type (card/mobile)
* Serial number
* Cash balance
* Last update time
* Last updating terminal
* Total transaction count

# Verification 

To verify, use a Flipper zero to read any Clipper card or virtual card (such as the Clipper App for Apple Watch or iOS device). I have tested this decoder against 10 clipper cards and two mobile cards.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by gornekich** [comment]
Thanks for PR!
Could you please send .nfc file for verification? Clipper app is not available in my region. You can attach file here or send me DM in Discord gornekich

**Comment by ke6jjj** [comment]
Sure. I had refrained from attaching it here due to privacy reasons.

**Comment by gornekich** [comment]
When I open files that you sent me, flipper crashes when I press Info in card menu. I am working on DESFire fixes right now, can't verify your plugin right now. I will come back once I finish DESFire fixes, hopefully on this week

**Review by gornekich — APPROVED** [review]
Tested this PR after some DESFire fixes - everything works great. Thanks!

**Review by hedger — APPROVED** [review]

**Pull request merged**
