### PR TITLE
Add support for `R_ARM_REL32` relocations.

### PR DESCRIPTION
**Pull request by Sameesunkaria**
# What's new

Add support for `R_ARM_REL32` relocations.

It is fairly straightforward to correctly resolve an `R_ARM_REL32` relocation as described in in the "Relocation types" section of [ARM ELF Specification](https://developer.arm.com/documentation/espc0003/1-0/?lang=en). It modifies the 32-bit word at the address being relocated, just like `R_ARM_ABS32`, but the value is resolved using the following formula:

```
S - P + A
```

where `S` is the value of the symbol (`symAddr`), `P` is the address of the place being relocated (`relAddr`), and `A` is the addend (value extracted from the storage unit being relocated, in this case).

I encountered the `R_ARM_REL32` relocation type as part of my work for [building apps written in Swift](https://github.com/Sameesunkaria/swift-flipperzero-hello) for the Flipper Zero.

# Verification 

I have manually tested that this relocation works correctly by building and running multiple apps that depend on this relocation being performed correctly.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by hedger — APPROVED** [review]

**Comment by Sameesunkaria** [comment]
@hedger please let me know if you need a pre-compiled `fap` that requires `R_ARM_REL32` relocations to help validate this change.

**Comment by skotopes** [comment]
@Sameesunkaria yes, we do need it

**Comment by Sameesunkaria** [comment]
Here's the `.fap`: [Hello.fap.zip](https://github.com/flipperdevices/flipperzero-firmware/files/15283896/Hello.fap.zip) 

It's compiled from the sources found on my repository: https://github.com/Sameesunkaria/swift-flipperzero-hello. The app fails to load with the error code "MissingImports" when you try launching it without the changes in this PR. You should see "Undefined relocation 3" in the logs.

Hope this helps :)

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
Seeing swift on flipper is really cool. Great work!

**Pull request merged**
