### PR TITLE
Mousejiggler

### PR DESCRIPTION
**Pull request by RogueMaster**
# What's new
I did not write the original app but I have updated it to work on the current firmware build

- added plug-in for mouse jiggler. When plugged in to PC, makes the mouse jiggle. May only work if flipper is closed. 

# Verification 

- open plugin, Connect to PC, hold center to start

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by DoberBit** [comment]
Just do translate this "нахуя?! Остановись!" I don't even want to argue my point

**Comment by RogueMaster** [comment]
> Just do translate this "нахуя?! Остановись!" I don't even want to argue my point

Hating much? Keep your contributions to something more useful 🙄

**Comment by DoberBit** [comment]
> > Just do translate this "нахуя?! Остановись!" I don't even want to argue my point
> 
> Hating much? Keep your contributions to something more useful 🙄

What do you mean by you "have refactored" that app?

I cant find at least one changed letter in "your" version
You just got it as is from here
https://github.com/Jacob-Tate/flipperzero-firmware/blob/dev/applications/mouse_jiggler/mouse_jiggler.c

Nothing changed, just manifest added

**Comment by Astrrra** [comment]
The same applies here.

https://github.com/flipperdevices/flipperzero-firmware/pull/1400#issuecomment-1186036550

**Comment by RogueMaster** [comment]
> The same applies here.
> 
> https://github.com/flipperdevices/flipperzero-firmware/pull/1400#issuecomment-1186036550

Updated comments

**Comment by RogueMaster** [comment]
@Jacob-Tate & @MuddledBox  this was mostly your code, someone requested it be PR'd so I have PR'd, hope you don't mind

**Comment by matslarson** [comment]
If it hasn't been modified from the original at all I don't think it will build. I was just working on getting this working with the new build toolchain when I stumbled on this PR, it threw errors about unused parameters and needs a couple declarations like `UNUSED(ctx)`
See https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/debug_tools/usb_mouse.c#L21 added in https://github.com/flipperdevices/flipperzero-firmware/pull/1185

**Comment by RogueMaster** [comment]
Refactored for future merge

**Comment by RogueMaster** [comment]
Since the moderators of this community don't enforce GPL restrictions on other members and moderators changing the licensing of an open source submission, I am withdrawing my Pull Request. GPL is made the way it is to avoid these problems. The moderators of the community are actively hindering the evolution of the project by going against GPL. Don't pretend to support open source and then go against it. Buyers beware!

**Pull request closed without merging**
