### PR TITLE
[FL-2633] Move files from /int to /ext on SD mount

### PR DESCRIPTION
**Pull request by nminaylov**
# What's new

- Moving files in app folders from internal storage to SD on SD card mount
- storage_common_merge

# Verification 

- Create some files on internal storage, insert SD card

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by RogueMaster** [comment]
Could this work to backup/restore the internal dolphin state and settings files?

**Comment by RogueMaster** [comment]
Nevermind, I see it can and it does. Thanks for the great work!

**Comment by RogueMaster** [comment]
Not sure if desired, but I made changes to allow for backup and no deletion of internal settings files.

https://github.com/RogueMaster/flipperzero-firmware-wPlugins/blob/unleashed/applications/storage_move_to_sd/storage_move_to_sd.c

**Comment by skotopes** [comment]
@RogueMaster make separate PR. This one is already full ;-)

**Review by skotopes — APPROVED** [review]

**Pull request merged**
