### PR TITLE
<DELETED>

### PR DESCRIPTION
**Pull request by gotnull**
<DELETE>

### CODE REVIEW

**Comment by Astrrra** [comment]
oh god

**Comment by gotnull** [comment]
> oh god

My mistake! Sorry!

**Comment by DrZlo13** [comment]
>Files changed 811, +231,507 −5,778 

I don't think it can be merged.

**Comment by Astrrra** [comment]
I think you are trying to merge the entire unleashed fork into this repo

**Comment by gotnull** [comment]
> > Files changed 811, +231,507 −5,778
> 
> I don't think it can be merged.

It was actually by accident because I thought I was creating a pull request on the custom firmware. Apologies!

**Comment by gotnull** [comment]
Whoops!

**Comment by skotopes** [comment]
Nope. There are so many issues with this PR. Please read contribution guide.

**Pull request closed without merging**
