### PR TITLE
[Subghz] External cc1101 module support

### PR DESCRIPTION
**Pull request by Shmuma**
# What's new

- SPI Hal: support of software spi mode (when `bus` field in spi handle is NULL)
- External CC1101 module attached to GPIO pins
- Settings option to switch between internal and external cc1101
- Documentation describing connection of modules (`documentation/ExtCC1101.md`)

Main motivation for this was to attach proper antennas to flipper without hardware modifiations.
As B3 is the only external pin with timer (with capture functionality), software spi was implemented.

There is alternative solution to this problem, which uses GPIO interrupts to measure the G0 pin signal. It makes the pinout more flexible and removes neccesity in software SPI, but requires modification of the subghz core functionality. This PR requires G0 to be attached to the B3 pin and due to this, software SPI is needed. On the flip side, modifications to the subghz internals are minor. As it is the same timer, all the receive and send routines are working without modifications. Due to this, risks of breaking subghz are minimal.

# Verification 

- Attach SPI CC1101 module as described in `ExtCC1101.md`
- Switch to external cc1101 in Settings -> Subghz
- Subghz and WeatherStation is using external cc1101 module (could be validated by detaching/attaching G0 pin)

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
We need some time to figure out what to do with this PR. I'll come back wth more information after this release cycle end.

**Comment by Shmuma** [comment]
> We need some time to figure out what to do with this PR. I'll come back wth more information after this release cycle end.

Sure, no rush! If you have any question I can answer, please let me know

**Comment by skotopes** [comment]
I need more time with this code, moving to next release.

**Comment by skotopes** [comment]
@Shmuma we are currently working on software SPI this PR will be merged after its completion.

**Comment by skotopes** [comment]
SubGhz was redesigned to support multiple device drivers in https://github.com/flipperdevices/flipperzero-firmware/pull/2747

I'll close this PR

**Pull request closed without merging**
