### PR TITLE
SubGhz: Add KaKu support

### PR DESCRIPTION
**Pull request by qistoph**
# What's new

- Add SubGhz support for the [Klik Aan Klik Uit protocol](https://forum.flipperzero.one/t/klik-aan-klik-uit-doorbells-wireless-dimmers-and-switches-eu/4337)

# Verification 

- Compile and flash. Check receiving / saving / loading / transmitting KaKu protocol
- (Reference captures and sample files available if requested)

# TODO

- [ ] Add unit tests

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by Skorpionm** [comment]
I am very glad that you are the first who is trying to add a new protocol for SubGhz? but you seem to have made a mistake, it is very similar to what you added
https://github.com/flipperdevices/flipperzero-firmware/pull/1622
https://forum.flipperzero.one/t/tri-state-for-remote-control-outlet-switches/5598/3

and you do not have a unit_test to check that your decoding method will not confuse with other protocols, and there are already a lot of them

**Comment by qistoph** [comment]
It is indeed also tri-state and uses short-long pulses to diffenriate. However, Kaku is still different:

|           | 0           | 1           | 'F'         |
|-----------|-------------|-------------|-------------|
| Tri-State | 1H,3L,1H,3L | 3H,1L,3H,1L | 1H,3L,3H,1L |
| Kaku      | 1H,1L,1H,3L | 1H,3L,1H,1L | 1H,1L,1H,1L |

For readability and maintenance I would think it's better to separate them.

I'm sorry for missing the unit_tests. There was no description of how to add protocols yourself and I didn't know about the unit tests. I'll add those.

**Comment by Skorpionm** [comment]
> 
no, you are a little wrong, I added a 3rd version of the protocol, not the one you described, this is the second one.  could you upload the raw recording of kaku, with and without dimming

**Comment by Skorpionm** [comment]
image
those you have in the signal are also 250..275 not 300.. long interval ~1500..1600 not 1200.

**Comment by Skorpionm** [comment]
image
your encoder is not working properly. although the description says that the upload is repeated 4 times in your SUB, this is not so, the transfer goes on while the button is held down. slightly incorrect timings during transmission. there is no guard time between sendings ..... Understand me correctly, I am by no means saying that you did everything badly .... YOU are the first who figured this out at least a little and I am ready to help in this endeavor, since I am also not rubber and help will come in handy

**Comment by qistoph** [comment]
Thanks for the feedback. Attached are two captures;

- [Kaku_001.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9382160/Kaku_001.sub.txt) - Off command
- [Kaku_002.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9382159/Kaku_002.sub.txt) - Dimm command

I can't figure out how to run the unit tests. I have found `./fbt FIRMWARE_APP_SET=unit_tests`, but this leaves my Flipper with only "Settings" and "Debug Tools" in the menu.

The encoder is indeed a bitt off. I think the issue is in `furi_hal_subghz_async_tx_refill` or `furi_hal_subghz_async_tx_dma_isr`, because it ends near the `API_HAL_SUBGHZ_ASYNC_TX_BUFFER_FULL` and it seems that my callback is not called again.

I was also having some issues with the high/low start. Which probably has to do with https://github.com/flipperdevices/flipperzero-firmware/blob/dev/firmware/targets/f7/furi_hal/furi_hal_subghz.c#L487, but messed up each of my highs by adding the `API_HAL_SUBGHZ_ASYNC_TX_GUARD_TIME`. See: https://discord.com/channels/740930220399525928/1009441815927210124. I worked around that by adding an initial low.

I'll give https://github.com/flipperdevices/flipperzero-firmware/pull/1622 a try and see if it recognizes my remotes.

**Comment by skotopes** [comment]
Basically unit tests are executed from device cli. And you need to upload assets/unit_tests folder to sd card root.

**Comment by Skorpionm** [comment]
> I'll give https://github.com/flipperdevices/flipperzero-firmware/pull/1622 a try and see if it recognizes my remotes.


yes check.  I checked the files attached on the forum, they work.  regarding the encoder, see my software, how it is implemented.  it completely repeats the received message

**Comment by qistoph** [comment]
> > Я попробую #1622 и посмотрю, распознает ли он мои пульты.
> 
> yes check. I checked the files attached on the forum, they work. regarding the encoder, see my software, how it is implemented. it completely repeats the received message

#1622 does work for the on/off commands on my remote. However, the dimm command seems to not be recognized. The dimm command is 4 bytes longer.

If the on/off command is not a '0' or '1', but the '1H,1L,1H,1L' sequence, there are 36 bits in the command. The last 4 bits are the dimm level.

Would it be possible to add that to #1622? If that's the case, you can completely ignore my PR and close it.

**Comment by Skorpionm** [comment]
yes, you can add, give me recordings with dimming on different channels, I don’t have this remote control, I do everything according to "photos".  but do not completely ignore you, choose which protocol you want to add and I will help you with your questions

**Comment by Skorpionm** [comment]
> * [Kaku_001.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9382160/Kaku_001.sub.txt) - Off command
> * [Kaku_002.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9382159/Kaku_002.sub.txt) - Dimm command

please give a RAW recording of the transmission of the remote control with dimming and crumples also with the name of the buttons that were pressed. not your saves

**Comment by qistoph** [comment]
> > * [Kaku_001.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9382160/Kaku_001.sub.txt) - Off command
> > * [Kaku_002.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9382159/Kaku_002.sub.txt) - Dimm command
> 
> please give a RAW recording of the transmission of the remote control with dimming and crumples also with the name of the buttons that were pressed. not your saves

I'm so sorry! What a rookie mistake...

I was a bit in a rush because of other plans. I'll get back to this after the weekend.

Thanks for all your kind suggestions

**Comment by tkerby** [comment]
> 

I think we may need in the future a means to select possible protocols to decode or potentially the flipper saves a raw then presents options. It's very difficult to test for random protocols otherwise

**Comment by Skorpionm** [comment]
> I think we may need in the future a means to select possible protocols to decode or potentially the flipper saves a raw then presents options. It's very difficult to test for random protocols otherwise

that's what unit_test is for. it contains heaps of mixed signals in RAW format and passing them through all decoders, we check that they work correctly and there are no false decodings

**Comment by Skorpionm** [comment]
@qistoph  I need records to fix PR

**Comment by qistoph** [comment]
With a bit of a delay here are three recordings:

- Device 1 on the remote, on command: [Stalamp_on.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9399556/Stalamp_on.sub.txt)
- Device 1 on the remote, off command: [Stalamp_off.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9399557/Stalamp_off.sub.txt)
- Device 6 on the remote, on command, followed by 2 dimming settings: [Gaaslamp.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9399555/Gaaslamp.sub.txt)

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/1622

@qistoph  check please

**Comment by qistoph** [comment]
Receiving the signals works flawlessly.

```
Intertechno 36b   433.92AM
Key:0x42D2E8854
Sn:10B4BA2
Ch:1010 Dimm:26%
```

When sending original on/off commands, my device respond properly. However, the dimm command didn't seem to work.

Comparing the signals, I've found the dimm bit in your implementation to be off.

Receiving bits are counted MSB to LSB, then the dimm bit is at index 27. Sending bits however are counted LSB to MSB, then the offset is 9 (36 total bits - 27 offset bits = 9).

Fixed the issue locally:
```patch
diff --git a/lib/subghz/protocols/intertechno_v3.c b/lib/subghz/protocols/intertechno_v3.c
index c99dc40f..e70bb8c8 100644
--- a/lib/subghz/protocols/intertechno_v3.c
+++ b/lib/subghz/protocols/intertechno_v3.c
@@ -122,7 +122,7 @@ static bool subghz_protocol_encoder_intertechno_v3_get_upload(
         level_duration_make(false, (uint32_t)subghz_protocol_intertechno_v3_const.te_short * 10);
     //Send key data
     for(uint8_t i = instance->generic.data_count_bit; i > 0; i--) {
-        if((instance->generic.data_count_bit == INTERTECHNO_V3_DIMMING_COUNT_BIT) && (i == 27)) {
+        if((instance->generic.data_count_bit == INTERTECHNO_V3_DIMMING_COUNT_BIT) && (i == 9)) {
             //send bit dimm
             instance->encoder.upload[index++] =
                 level_duration_make(true, (uint32_t)subghz_protocol_intertechno_v3_const.te_short);
```

I'll close this PR and will look forward to seeing #1622 being merged.

Thank for your efforts, time and supporting me in my trials.

**Pull request closed without merging**
