### PR TITLE
I²C-Scanner

### PR DESCRIPTION
**Pull request by GitChris3004**
# What's new

- adds I²C-Scanner which scans the I2C-Bus (SDA: Pin 15, SCL: Pin 16) for available 7-Bit slave addresses. 
- shows the number of detected slaves and their addresses (maximum of 8 addresses fit the screen).
i2c_scanner

# Verification 

- Connect one or multiple I²C components to the I²C-GPIOs of the Flipper (SDA: Pin 15, SCL: Pin 16, shared GND) 
- If your I²C-slave doesn't provide Pull-Up resistors you have to connect one 4k7 ohms resistor from SDA to 3V3 and one from SCL to 3V3
- Go to "GPIO"->"I2C-Scanner" and press the "ok" button to start the scan.
- The green LED will light up for half a second and after that the display will be updated with the number of slaves detected and their I²C-Addresses.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by xMasterX** [comment]
Hi, you forgot to exclude that file from PR
`assets/resources/Manifest`

**Comment by GitChris3004** [comment]
> Hi, you forgot to exclude that file from PR `assets/resources/Manifest`

Hey, thx i reversed my changes.

**Comment by skotopes** [comment]
Hi. Scheduled for next release.

**Comment by GitChris3004** [comment]
Hey, if there is anything i can do speeding up the merging process let me know.

**Comment by skotopes** [comment]
Hi @GitChris3004 

Sorry for delay, this PR is waiting for ELF support to be merged first.

**Comment by skotopes** [comment]
@GitChris3004 we've merged ELF support. How about moving this feature to external application?

**Comment by wdoekes** [comment]
Cool. I planned on doing a Onewire scanner too. Just waiting for #1635. @skotopes: do you have feedback there?

**Comment by GitChris3004** [comment]
> @GitChris3004 we've merged ELF support. How about moving this feature to external application?

Hey, that's nice. I will have access to my flipper in about 2 weeks again. Then I can resolve the remaining merging conflicts. What do you mean with moving it to external application?

**Comment by skotopes** [comment]
@GitChris3004 just change application type in .fam to the same value as in picopass app.

**Comment by skotopes** [comment]
We can accept it as external application. Meanwhile I'm closing this PR.

**Pull request closed without merging**
