### PR TITLE
[FL-2258] SubGhz: removal of frequencies

### PR DESCRIPTION
**Pull request by Skorpionm**
# What's new

- [FL-2258] SubGhz: removal of frequencies

# Verification 

- compile flash
- run SubGhz app -> Read check available frequencies in config

# Checklist (do not modify)

- [X] PR has description of feature/bug or link to Confluence/Jira task
- [X] Description contains actions to verify feature/bugfix
- [X] I've built this code, uploaded it to the device and verified feature/bugfix

[FL-2258]: https://flipperzero.atlassian.net/browse/FL-2258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by skotopes — APPROVED** [review]

**Comment by wbraswell** [comment]
@Skorpionm @skotopes @DrZlo13 
Why was 300MHz removed???
(I'm trying to request access to the Jira for this issue, but when I click on the "Request Access to Jira" button nothing happens.)

**Comment by skotopes** [comment]
@wbraswell 300mhz was test frequency meant to be used on factory tests.

Our antenna and matching networks doesn't work well on this frequency.

Do you have devices that run on this frequency?

**Comment by wbraswell** [comment]
Yes, my garage door opener is 300MHz.  I had already saved a copy of it, which no longer shows up after my firmware upgrade.  I had also saved a copy of my TV infrared remote control, which does show up in the menu but does nothing when I click on it.

**Comment by wbraswell** [comment]
My SubGHz frequency analyzer won't even show my garage door opener at all any more!

**Comment by skotopes** [comment]
As for garage door opener can you provide fcc id? we'll return frequency in next release.

As for infrared: can you open new issue? it looks like a bug

**Comment by wbraswell** [comment]
Done!
#1031
#1032 
Also, please add me to Jira: william.braswell@autoparallel.com

**Pull request merged**
