### PR TITLE
Refactor build status display code

### PR DESCRIPTION
**Pull request by DXVVAY**
# What's new

- Imported the Errors module from SCons.Script to avoid repeated references to SCons.Errors.

- using f strings for string formatting for better readability.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
See build errors. Un-draft when ready.

**Comment by DXVVAY** [comment]
> See build errors. Un-draft when ready.

that should fix it

**Comment by thefirans** [comment]
Worked out for me

**Comment by hedger** [comment]
Appreciate you pointing out issues with that code, however, it needs a deeper rework. It will be done soon.

**Pull request closed without merging**
