### PR TITLE
[WIP] Gpio menu rework

### PR DESCRIPTION
**Pull request by g3gg0**
Based on PulseReader branch, thus a few more commits on the history here

# What's new

 - showing current in/out status by inverting the IO status icon
 - added modes: [I] input, [O] output, [S] signal. [A] analog will follow
 - each IO can be configured independently
 - signal generators currently implemented: 
    - WS2812: will fade all 3/4 color channels of the selected LED (only one LED will be lit -> current..)
    - PWM: two IOs A7 and A4 support PWM generation. selecting frequency/duty is not user friendly. still needs a proper input handling
    - servo: generates a 50/100/200 Hz servo signal with only 5 angles (PWM generator has only 1% duty cycle accuracy)
 - every IO being configured for e.g. WS2812 will output the same signal
 - added advanced PWM, allowing any GPIO to output the signal

# Video
https://cdn.discordapp.com/attachments/954430078882816021/1064604285234589746/qFlipper_2023-01-16_18-55-36.mp4

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by g3gg0** [comment]
Can you please check the way i changed the view stuff in gpio_test.c, if that matches how it shall be used?

**Comment by skotopes** [comment]
Looks like this should be in https://github.com/flipperdevices/flipper-application-catalog

**Comment by g3gg0** [comment]
not sure if this even compiles after the changes that have been made to the project since then :D

**Comment by skotopes** [comment]
Should be totally feasible, not much changes was made in that area ;-)

**Pull request closed without merging**
