### PR TITLE
Added NFC plugin; parser for WashCity cards.

### PR DESCRIPTION
**Pull request by yaba**
# What's new

- Added new NFC plugin to read/parse WashCity (MarkItaly) cards.

# Verification 

- Added App in application.fam
- Added new file washcity.c
- Parser reads serial number and current balance in Euros.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by hedger** [comment]
Could you also provide sample card dumps for testing?

**Comment by yaba** [comment]
> Could you also provide sample card dumps for testing?

Sure, allow me a couple of minutes. BTW, seems that I've messed up the file path, it's now fixed.

**Comment by hedger** [comment]
Please build the firmware locally and run linters.

**Comment by yaba** [comment]
> Please build the firmware locally and run linters.

Done, sorry.

**Review by gornekich — CHANGES_REQUESTED** [review]
Thanks, looks good!
Please, remove Demo_WC_20E.nfc file from resources and we will merge it. Example dump shouldn't be part of nfc resources.

**Review by gornekich — APPROVED** [review]
Thanks!

**Review by skotopes — APPROVED** [review]

**Pull request merged**
