### PR TITLE
Updated Universal Remote (all buttons)

### PR DESCRIPTION
**Pull request by UberGuidoZ**
# What's new

- Adds the ability to use the volume/channel buttons within the existing Universal remote

# Verification 

- Compiled by Hyper_Mash with support/testing by UberGuidoZ
- Verified on current firmware releases (Official, Unleashed, RogueMaster)
- Remote can freeze up to 10 seconds at a time; this is normal while it skips other button functions.
- EVERY button completes and does not crash; size optimized and tested.
- Plan to maintain with additions as they come in from other IR files AND more organization.
- Lastly, plans to add other devices beyond TV (AV, AC, etc.)

# Checklist (For Reviewer)

- [ ] PR has a description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device, and verified the feature/bugfix

### CODE REVIEW

**Comment by UberGuidoZ** [comment]
Currently hosted here: https://github.com/UberGuidoZ/Flipper/tree/main/Infrared
Discussion started: https://discord.com/channels/740930220399525928/954422774141710366/993703699316756561
Released: https://discord.com/channels/740930220399525928/954422774141710366/994119260139950130
Optimized: https://discord.com/channels/740930220399525928/954422774141710366/994120897780781106
Tested: https://discord.com/channels/740930220399525928/954422774141710366/994123369148588072

**Comment by skotopes** [comment]
Scheduled for 0.63, we'd like to make couple improvements in file loading first.

**Comment by UberGuidoZ** [comment]
Thanks [skotopes](https://github.com/skotopes)! I edited the file after some assistance from c-nagy after a major reduction in duplicates. Looking forward to the optimized file loading!

**Comment by UberGuidoZ** [comment]
We now have AC and Soundbar/Speaker files as well. [Loader scene](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/infrared/scenes/infrared_scene_universal.c) will need to be updated to add them too.

**Pull request closed without merging**
