### PR TITLE
Infrared: add TCL 75S451 to TV universal remote

### PR DESCRIPTION
**Pull request by christhetech131**
# What's new

- Added TCL 75S451

# Verification 

- Use Universal Remote on TV

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
@christhetech131 please fill PR description. It will be nice to know what vendor/model you adding.

**Comment by skotopes** [comment]
Un-draft when ready

**Review by christhetech131 — COMMENTED** [review]
I uploaded this to flipper manually to verify.

**Review by christhetech131 — COMMENTED** [review]
Updated requested information.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
