### PR TITLE
Change default keyboard to Uppercase

### PR DESCRIPTION
**Pull request by DrEverr**
# What's new

According to Issue #1546 . Changed default keyboard to be displayed Uppercase. Because keyboard clears the screen and writes uppercase letter, even though displaying lowercase keyboard.

**[It just checks if "clear text" is set and than displays uppercase keyboard.](#)**

Before:
Screenshot-20220817-163637
Screenshot-20220817-163847

After:
Zrzut ekranu 2022-08-5 o 20 37 19
Zrzut ekranu 2022-08-17 o 16 40 03

Letter we are inputting is uppercase letter so keyboard also displays uppercase letters.

# Verification 

Even if text is present in text_box, we have displayed uppercase keyboard. Because we will input uppercase letter first.
Build project and install it on your Flipper and see if you like it. I think it's more intuitive this way. It displays what it inputs.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by DrEverr** [comment]
Merged with newest version of code.

**Comment by DrEverr** [comment]
I'm asking for feedback :D
It's not big change, but I think it upgrades comfort of using keyboard. If we gonna input first letter uppercase its good to show that on keyboard @hedger what ya think? ;D

**Comment by skotopes** [comment]
Looks like there are some merge artifacts in this PR: littlefs module should not be modified.

**Comment by DrEverr** [comment]
but how to fix it now 😖
my change is not that big, but I found it useful in UX meaning

**Review by skotopes — APPROVED** [review]

**Pull request merged**
