### PR TITLE
nfc: DESFire fixes

### PR DESCRIPTION
**Pull request by kevinwallace**
# What's new

- Fix reading DESFire cards which refuse GET_KEY_SETTINGS
- Fix saving DESFire cards with 0 applications

# Verification 

- Read a DESFire card that refuses GET_KEY_SETTINGS, verify read completes (previously it would `FURI_LOG_W` in a loop)
- Save a DESFire card that has no applications, verify card data is saved and no error is shown (previously, card data would be saved but an error would be shown)

A "UniFi Access" card can be used to test both of the above scenarios.

flipper_ui_access

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by gornekich** [comment]
Hello @kevinwallace !
I noticed that after saving card with 0 apps flipper crashes when you try to load that card. Back trace shows that you want to allocate 0 bytes:
```
#0  __furi_halt () at /home/nikita/localgit/flipperzero-firmware-community/core/furi/check.c:28
#1  0x08001478 in furi_crash (message=message@entry=0x80b3ab0 "furi_check failed\r\n")
    at /home/nikita/localgit/flipperzero-firmware-community/core/furi/check.c:54
#2  0x08002c12 in pvPortMalloc (xWantedSize=<optimized out>, xWantedSize@entry=0)
    at /home/nikita/localgit/flipperzero-firmware-community/core/furi/memmgr_heap.c:480
#3  0x08003662 in malloc (size=size@entry=0) at /home/nikita/localgit/flipperzero-firmware-community/core/furi/memmgr.c:12
#4  0x0804491c in nfc_device_load_mifare_df_data (file=file@entry=0x2000ff80, dev=dev@entry=0x20012248)
    at /home/nikita/localgit/flipperzero-firmware-community/applications/nfc/nfc_device.c:545
#5  0x08044c36 in nfc_device_load_data (dev=dev@entry=0x20012248, path=path@entry=0x200132e0)
    at /home/nikita/localgit/flipperzero-firmware-community/applications/nfc/nfc_device.c:867
#6  0x08044e7a in nfc_file_select (dev=0x20012248) at /home/nikita/localgit/flipperzero-firmware-community/applications/nfc/nfc_device.c:920
#7  0x0803e83c in nfc_scene_file_select_on_enter (context=0x20011d98)
    at /home/nikita/localgit/flipperzero-firmware-community/applications/nfc/scenes/nfc_scene_file_select.c:6
#8  0x08009d6c in scene_manager_next_scene (scene_manager=0x20012020, next_scene_id=next_scene_id@entry=7)

```
Could you please fix it in this PR?
Looks like we want to add some logic in nfc_device.c:545

**Review by gornekich — CHANGES_REQUESTED** [review]
Please, add support for loading cards with 0 App count

**Comment by kevinwallace** [comment]
Oops, sorry, I should have caught that!  Thanks for the stack trace.  Fixed in 1464afd6fd03eb1ef8fd0a3532f96496163ba77f, and verified saving *and loading* with the card shown in the photo above.

(Also, noted that 0-byte mallocs are unsupported, will avoid those in the future)

**Review by gornekich — APPROVED** [review]
Thanks!

**Review by skotopes — APPROVED** [review]

**Pull request merged**
