### PR TITLE
bit_lib and nfc_util refactor

### PR DESCRIPTION
**Pull request by Leptopt1los**
# What's new

- lfrfid bit_lib helper now is standalone lib
- _nfc_util_num2bytes_ is now **bit_lib_num_to_bytes_be**
- _nfc_util_bytes2num_ is now **bit_lib_bytes_to_num_be**
- _nfc_util_bytes2num_little_endian_ is now **bit_lib_bytes_to_num_le**
- **bit_lib_num_to_bytes_le** function added
- **bit_lib_bytes_to_num_bcd** function added
- **bit_lib_get_bits_64** function added
- unit tests updated

# Verification 
- build the firmware
- run unit_tests bit_lib in flipper cli

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by gornekich** [comment]
Hello @Leptopt1los 
Removing nfc_util_bytes2num(), nfc_util_bytes2num_little_endian(), nfc_util_num2bytes() from public API must end up with major API version bump. Also it breaks applications, which call these functions.
Did you edit API version in api_symbols.csv file?

**Comment by gornekich** [comment]
Alright, I see that the API version was bumped in merge commit 8a5cbfb. However the changes in this PR require to bump major version manually. Also applications which use removed nfc_util_*functions will be broken.

**Comment by Leptopt1los** [comment]
> Alright, I see that the API version was bumped in merge commit [8a5cbfb](https://github.com/flipperdevices/flipperzero-firmware/commit/8a5cbfb4e63086ea1d79d10cc6f37288a5ff3d96). However the changes in this PR require to bump major version manually. Also applications which use removed nfc_util_*functions will be broken.

a little later I will bump the api version manually. As for applications that use nfc_util - I replaced calls to these functions with new ones throughout the repository. am I required to replace them in the flipper zero good faps repository? or somewhere else?

**Comment by Leptopt1los** [comment]
@gornekich API version bumped, last dev branch changes merged. PR is ready to review

**Comment by gornekich** [comment]
@Leptopt1los we are OK with breaking API. Please update PR with latest changes and we will merge it

**Comment by Leptopt1los** [comment]
@gornekich build errors fixed, PR is ready to merge

**Review by gornekich — APPROVED** [review]
Thanks

**Review by skotopes — APPROVED** [review]

**Review by skotopes — APPROVED** [review]

**Pull request merged**
