### PR TITLE
[FL-3100] SubGhz: add protocol Nice One

### PR DESCRIPTION
**Pull request by Skorpionm**
# What's new

- [FL-3100] SubGhz: add protocol Nice One

# Verification 

- Run SubGhz Read, check the reception of the new system

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

[FL-3100]: https://flipperzero.atlassian.net/browse/FL-3100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by skotopes — APPROVED** [review]

**Comment by MaxexaM** [comment]
hi, is there any news for Nice one remote controls? I am currently unable to download the firmware. Thans

**Comment by skotopes** [comment]
> hi, is there any news for Nice one remote controls? I am currently unable to download the firmware. Thans

As this PR states nice one support was merged and available in latest release

**Comment by MaxexaM** [comment]
> > salve, ci sono novità per i telecomandi Nice one? Al momento non riesco a scaricare il firmware. Grazie
> 
> Come afferma questo PR, Nice One Support è stato unito e disponibile nell'ultima versione

maybe it's my problem, but the files to be downloaded are not accessible :(
error: 404 not found

**Comment by skotopes** [comment]
Which files?

The one that was attached to this PR is only for testing before PR merge. After PR merge they are removed and changes arrives to Dev channel.

**Comment by MaxexaM** [comment]
> Quali file?
> 
> Quello che è stato allegato a questo PR è solo per il test prima dell'unione di PR. Dopo l'unione delle PR vengono rimosse e le modifiche arrivano al canale Dev.

ok. you will have understood that I am new to the Flipper world, I was thinking of installing the DATABASE of the Nice remote controls but I understood that this github is the wrong way

**Pull request merged**
