### PR TITLE
Rework storing Indala cards to support any scramble

### PR DESCRIPTION
**Pull request by ezhevita**
# What's new

- Added storing checksum for Indala cards

# Verification 

- Any cards with different checksum should be read and emulated properly. All new cards should have checksum when saved.

# Checklist (do not modify)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by DrZlo13** [comment]
You cannot simply remove the checksum calculation. 28 bits of data are scrambled, and if we expand support for the Indala format, then we need to remake the key store format to store all 28 bits.

**Review by DrZlo13 — CHANGES_REQUESTED** [review]
You cannot simply remove the checksum calculation. 28 bits of data are scrambled, and if we want to expand support to the all Indala formats, then we need to remake the key store format to store all 28 bits.

**Comment by skotopes** [comment]
Any progress on this PR?

**Comment by ezhevita** [comment]
It's ready for a review, and @aprosvetova said that protobuf status check failing is fine

**Comment by ezhevita** [comment]
Converter for old format: https://github.com/Vital7/FlipperIndalaMigrator

**Comment by skotopes** [comment]
Ok. Waiting for approve from @DrZlo13

**Comment by DrZlo13** [comment]
To clarify things, this pull request is waiting for me to test Indala card reading without verifying the checksum.

**Comment by ezhevita** [comment]
Any progress on this?

**Comment by skotopes** [comment]
@Vital7 yep, sorry for delay, this task connected with another one: rfid refactoring W'ell do tests and merge this one

**Comment by ezhevita** [comment]
btw, it doesn't work, apparently
original and emulated IDs are different by 1 bit

**Comment by DrZlo13** [comment]
Done in #1601

**Pull request closed without merging**
