### PR TITLE
Documentation: fixed outdated naming

### PR DESCRIPTION
**Pull request by DrEverr**
Changed because of outdated naming in assets/dolphin/ReadMe. `essential -> blocking`

# What's new

- Correct file naming in ReadMe's (`assets/dolphin/ReadMe.md` and `assets/ReadMe.md`)

# Verification 

- Check naming of files in path `assets/dolphin/` and `assets/`
or 
- Check how `assets/SConscript` names files and folders

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
Hi. I think we also need to rename assets files.

**Comment by skotopes** [comment]
@DrEverr Can you also do it?

**Comment by DrEverr** [comment]
Yes. I'll look at it today.

**Comment by DrEverr** [comment]
Hi @skotopes, done. Open for feedback if I wrote something wrong.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
