### PR TITLE
[FL-2874] Remove bank card uid emulation

### PR DESCRIPTION
**Pull request by gornekich**
# What's new

- Remove bank card uid emulation from application and archive

# Verification 

- Flipper doesn't emulate bank card uid anymore

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by Yoanndp** [comment]
Hello, can you explain what's the point ?

**Comment by kenayagi** [comment]
> Hello, can you explain what's the point ?

Yes, please. I'm missing it too... 🤔

**Comment by Yoanndp** [comment]
> > Hello, can you explain what's the point ?
> 
> Yes, please. I'm missing it too... 🤔

The UID Emulation has been removed because it doesn’t do anything useful (the UID is not enough to clone/emulate a bank card).

_Thanks Equip#1515_

**Review by skotopes — APPROVED** [review]

**Comment by dogtopus** [comment]
For those wondering how you can still use this feature (yes): Go to `Extra Actions -> Read Specific Card Type -> Read NFC-A Data`. As previously stated this will NOT allow you to clone them, but if you just want the UID for e.g. some crappy locks that authenticate based on NFC-A UID, this is the way to do it.

**Pull request merged**
