### PR TITLE
Fix quoted error for macOS bad-usb

### PR DESCRIPTION
**Pull request by elulcao**
# What's new

- Fixed double quotes that was interpreted as an error. 

Screenshot 2022-12-19 at 9 19 39 PM

# Verification 

- Executed new `demo_macos` bad-usb example in a macOS machine.
- Extra colors comes from my personal zsh configuration.

Screenshot 2022-12-20 at 10 22 23 AM

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
The best option will be to fix escaping itself. Can you do that?

**Comment by elulcao** [comment]
> The best option will be to fix escaping itself. Can you do that?

Agree, I removed the redirect so the code it's like before. The problem is the backtick, replacing it with simple quote avoids command substitution.

**Review by skotopes — APPROVED** [review]

**Comment by elulcao** [comment]
Hello @skotopes 

Thanks for reviewing the change, 👍 
I saw there is an [error with](https://github.com/flipperdevices/flipperzero-firmware/actions/runs/3783484973/jobs/6432069333) "Build / main (pull_request)" about `Invalid bucket name ""`, I couldn't figured out how to fix it nor starting again the check; do you mind letting me know if I have to do something to re-run the check.

**Comment by skotopes** [comment]
@elulcao nah, that was issue on our side. Now it's fixed.

**Pull request merged**
