### PR TITLE
Upside down / left handed orientation support

### PR DESCRIPTION
**Pull request by hramrach**
# What's new

- rtc flag for orienatation
- gui code making use of the flag

# Verification 

- In system settings set the Lefty orienatation
- verify screen is upside down
- verify directional button actions are inverted to match screen
- verify directional keys work correctly on screen with vertical orientation

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by WillyJL** [comment]
If youre gonna take stray commits from other places, PLEASE talk with the author first. It is both out of respect, and for sake of sanity. I updated the code in a later commit. This current implementation has issues in vertical view ports, with it still flipping inputs ignoring the orientation. A simple @Willy-JL tag would have been fine you know, just to make me aware

**Comment by WillyJL** [comment]
https://github.com/ClaraCrazy/Flipper-Xtreme/commit/89e5b479c8fa1f17fa98a937340d1a00af2a9018

**Comment by hramrach** [comment]
> [ClaraCrazy@89e5b47](https://github.com/ClaraCrazy/Flipper-Xtreme/commit/89e5b479c8fa1f17fa98a937340d1a00af2a9018)

Thanks for the fix

**Comment by hramrach** [comment]
> If youre gonna take stray commits from other places, PLEASE talk with the author first. It is both out of respect, and for sake of sanity. I updated the code in a later commit. This current implementation has issues in vertical view ports, with it still flipping inputs ignoring the orientation. A simple @Willy-JL tag would have been fine you know, just to make me aware

As for talking to people - you released the thing under GPL3 so people are free to use it.

Some people like to know everything about their code, some are bothered by excessive notifications. Can't read your mind.

Unless clearly stated otherwise I use the platform default which is to not notify on github.

**Review by DrZlo13 — APPROVED** [review]

**Review by skotopes — APPROVED** [review]

**Pull request merged**
