### PR TITLE
Infrared: RCA protocol support

### PR DESCRIPTION
**Pull request by xMasterX**
# What's new

- Added `RCA` protocol - Used by Thomson, TCL, and many other manufacturers
- Updated Docs to add list of supported protocols for `parsed` type
- PR #2818 can be merged after this PR

# Verification 

- Try receive and send for TCL or Thomson TV remotes, they should be decoded and parsed not as RAW now, sending should work too -> All was tested and verified to be working good

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
We need some data for unit tests

**Comment by xMasterX** [comment]
> We need some data for unit tests

I can provide only raw captures of TCL remote, what exactly is needed?

```
#
# TCL LED49D2930
#
name: Power
type: raw
frequency: 38000
duty_cycle: 0.330000
data: 3994 3969 552 1945 551 1945 552 1945 551 1945 552 946 551 947 550 1947 548 951 546 1953 542 979 518 1979 517 981 492 1006 491 1006 492 1006 492 1006 492 2005 492 2005 492 1006 492 2005 492 1006 492 2005 492 1006 492 2006 491 9051 3963 3999 491 2006 491 2006 491 2006 491 2006 491 1007 491 1007 491 2006 491 1007 491 2006 491 1007 491 2006 491 1007 491 1007 491 1007 491 1006 492 1007 491 2006 491 2006 491 1007 491 2006 491 1007 491 2006 491 1007 491 2006 491 9052 3962 4000 491 2006 491 2006 491 2006 491 2006 491 1007 491 1007 491 2006 491 1007 491 2006 491 1007 491 2006 491 1007 491 1007 491 1007 491 1007 491 1007 491 2006 491 2007 490 1007 491 2006 491 1007 491 2006 491 1007 491 2006 490
#
name: Vol_up
type: raw
frequency: 38000
duty_cycle: 0.330000
data: 4055 3941 605 1891 551 1947 550 1946 551 1946 551 947 551 947 550 1947 549 949 548 1951 545 1977 519 1978 519 1979 518 980 518 980 518 980 518 980 518 1979 518 1979 518 981 517 1979 518 980 518 980 518 980 518 980 518 9026 3989 3975 517 1980 517 1980 517 1979 518 1980 517 980 518 980 518 1979 518 981 517 1980 517 1980 517 1980 517 1980 517 980 518 981 517 981 517 981 517 1980 517 1980 517 981 517 1980 517 981 517 981 517 981 517 981 517 9027 3988 3975 517 1980 517 1980 517 1980 517 1980 516 981 517 982 516 1981 516 982 516 1981 516 1981 516 1981 516 1981 516 982 516 982 515 982 516 982 516 1982 515 1981 516 982 515 1981 516 983 515 982 516 982 515 982 516
#
name: Vol_dn
type: raw
frequency: 38000
duty_cycle: 0.330000
data: 4027 3970 551 1946 550 1946 551 1946 551 1946 551 946 551 947 550 1947 549 949 547 1951 545 1978 518 1979 492 1006 492 1007 491 1006 492 1006 492 1006 492 2006 491 2006 491 1006 492 2006 491 1007 491 1007 491 1006 492 2006 491 9053 3964 4000 491 2006 491 2006 491 2006 491 2006 491 1007 491 1007 491 2006 491 1007 491 2006 491 2006 491 2006 491 1007 491 1007 491 1007 491 1007 491 1007 491 2006 491 2006 491 1007 491 2006 491 1007 491 1007 491 1007 491 2006 491 9053 3963 4001 491 2006 491 2006 491 2007 490 2007 490 1007 491 1007 491 2007 490 1007 491 2006 491 2006 491 2007 490 1008 490 1007 491 1008 490 1007 491 1008 490 2007 490 2007 490 1008 490 2007 490 1008 490 1008 489 1008 490 2007 490
#
name: Ch_next
type: raw
frequency: 38000
duty_cycle: 0.330000
data: 4021 3941 551 1946 550 1946 551 1946 551 1945 552 946 551 947 550 1947 549 950 547 1952 544 1977 519 979 519 1979 518 980 518 980 518 980 518 980 518 1979 518 1979 518 980 518 1979 518 980 518 980 518 1979 518 980 518 9026 3990 3974 517 1980 517 1980 517 1980 517 1980 517 981 517 981 517 1980 517 981 517 1979 518 1979 518 980 517 1980 517 981 517 981 517 981 517 980 518 1980 517 1980 517 980 517 1980 517 981 516 981 517 1980 517 981 516
#
name: Ch_prev
type: raw
frequency: 38000
duty_cycle: 0.330000
data: 4022 3941 551 1946 551 1946 577 1919 578 1919 578 920 552 946 551 1946 550 947 550 1949 547 1952 544 978 520 979 519 980 518 980 518 980 518 980 518 1979 518 1979 518 980 518 1979 518 980 518 980 518 1979 518 1980 517 9027 3990 3974 517 1980 517 1980 517 1980 517 1980 517 981 517 981 517 1980 517 981 517 1980 517 1980 517 981 517 981 517 981 517 981 517 981 517 981 517 1980 517 1980 517 981 517 1980 517 981 517 982 491 2006 516 1981 516
#
name: Mute
type: raw
frequency: 38000
duty_cycle: 0.330000
data: 3995 3968 552 1944 552 1946 550 1946 550 1946 551 947 550 948 549 1947 549 1949 547 1952 544 1978 518 1979 492 2005 492 1006 492 1006 492 1006 492 1006 492 2005 492 2005 492 1006 492 1006 492 1006 492 1006 492 1006 492 1006 492 9051 3963 4000 491 2005 492 2006 491 2006 491 2006 491 1007 491 1007 491 2006 516 1981 516 1980 491 2006 517 1980 517 1980 517 981 517 981 517 981 517 981 517 1980 517 1981 516 981 517 981 517 981 517 981 517 981 491 1007 491 9052 3988 3975 491 2006 491 2006 491 2006 514 1983 490 1007 491 1007 491 2006 491 2006 491 2006 491 2006 491 2006 491 2006 512 986 491 1007 491 1007 491 1007 491 2006 491 2006 491 1007 491 1007 490 1007 491 1007 491 1008 490 1007 491
```


And same remote but decoded

```
#
# TCL LED49D2930
# 
name: Power
type: parsed
protocol: RCA
address: 0F 00 00 00
command: 54 00 00 00
# 
name: Mute
type: parsed
protocol: RCA
address: 0F 00 00 00
command: FC 00 00 00
# 
name: Ch_next
type: parsed
protocol: RCA
address: 0F 00 00 00
command: B4 00 00 00
# 
name: Ch_prev
type: parsed
protocol: RCA
address: 0F 00 00 00
command: 34 00 00 00
# 
name: Vol_up
type: parsed
protocol: RCA
address: 0F 00 00 00
command: F4 00 00 00
# 
name: Vol_dn
type: parsed
protocol: RCA
address: 0F 00 00 00
command: 74 00 00 00
#
```

**Comment by gsurkov** [comment]
@xMasterX For the unit tests, a special file format is used which is described in the [documentation](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/file_formats/InfraredFileFormats.md#infrared-test-file-format). It is basically a regular .ir format but with some special keywords. Please put the unit test data file in the directory specified below.

You can also take a look at some [example files](https://github.com/flipperdevices/flipperzero-firmware/tree/dev/assets/unit_tests/infrared) for other protocols.

If you could also implement the [unit tests](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/debug/unit_tests/infrared/infrared_test.c) for your protocol, that would be wonderful! The how-to can be found [here](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/UnitTests.md#infrared).

**Comment by xMasterX** [comment]
> @xMasterX For the unit tests, a special file format is used which is described in the [documentation](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/file_formats/InfraredFileFormats.md#infrared-test-file-format). It is basically a regular .ir format but with some special keywords. Please put the unit test data file in the directory specified below.
> 
> You can also take a look at some [example files](https://github.com/flipperdevices/flipperzero-firmware/tree/dev/assets/unit_tests/infrared) for other protocols.
> 
> If you could also implement the [unit tests](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/debug/unit_tests/infrared/infrared_test.c) for your protocol, that would be wonderful! The how-to can be found [here](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/UnitTests.md#infrared).

Okay, thx, Ill try to add unit test today-tomorrow

**Comment by xMasterX** [comment]
@gsurkov 

All done, test added and works correctly

```
Leaked: 0
Status: PASSED
```

**Review by skotopes — APPROVED** [review]

**Pull request merged**
