### PR TITLE
Furi: getter for current thread stdout write callback

### PR DESCRIPTION
**Pull request by Milk-Cool**
# What's new

Added a getter for the current thread stdout callback

# Verification 

Try to get the current callback in an app.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
And use cases are?

**Comment by Milk-Cool** [comment]
> And use cases are?

I know this is a little specific, but you may need to set the callback when there already is one (for example, set by the cli service or by yourself earlier).

**Comment by Milk-Cool** [comment]
Here's a code snippet where this can be useful:
```c
static FuriString* execute_command_listen(FuriString* command, Cli* cli){
  FuriString* output = furi_string_alloc_set_str("");
  void cb(const char* data, size_t size){
    UNUSED(size);
    furi_string_cat_str(output, data);
  }
  FuriThread* thread = furi_thread_get_current();
  FuriThreadStdoutWriteCallback old_cb = thread->output.write_callback;
  furi_thread_set_stdout_callback(cb);
  execute_command(command, cli, false);
  furi_thread_set_stdout_callback(old_cb);
  return output;
}
```

This function executes a command and returns its output as a FuriString. However it won't work since the type FuriThread is not public, so we need th replace lines 7 & 8 with `FuriThreadStdoutWriteCallback cb = furi_thread_get_stdout_callback()`.
This function can be called by other commands so I need it to be able to work recursively.

**Comment by skotopes** [comment]
> Here's a code snippet where this can be useful:
> 
> ```c
> static FuriString* execute_command_listen(FuriString* command, Cli* cli){
>   FuriString* output = furi_string_alloc_set_str("");
>   void cb(const char* data, size_t size){
>     UNUSED(size);
>     furi_string_cat_str(output, data);
>   }
>   FuriThread* thread = furi_thread_get_current();
>   FuriThreadStdoutWriteCallback old_cb = thread->output.write_callback;
>   furi_thread_set_stdout_callback(cb);
>   execute_command(command, cli, false);
>   furi_thread_set_stdout_callback(old_cb);
>   return output;
> }
> ```
> 
> This function executes a command and returns its output as a FuriString. However it won't work since the type FuriThread is not public, so we need th replace lines 7 & 8 with `FuriThreadStdoutWriteCallback cb = furi_thread_get_stdout_callback()`. This function can be called by other commands so I need it to be able to work recursively.

Do you have application that already uses this API?

**Comment by Milk-Cool** [comment]
> Do you have application that already uses this API?

Yes I am writing an application, I took the code snippet from its code

**Comment by Milk-Cool** [comment]
If you are wondering if I've tested the function - yes I have

**Comment by skotopes** [comment]
> If you are wondering if I've tested the function - yes I have

Not really. More like all changes to Furi need solid reasoning why. Usually it's some real use examples.

**Comment by Milk-Cool** [comment]
> Not really. More like all changes to Furi need solid reasoning why. Usually it's some real use examples.

Alright so I'm writing an extra commands pack because I felt like the set of commands already included in the firmware lacked a lot of necessary ones. And there's the `if` command which takes two other commands as an argument and if command1 output is non-empty, it executes command2. The catch here is if we want to combine it with the `not` command which is kinda self-explanatory, both use this function and the function eventualy calls itself and if it sets the callback to default cli callback it just breaks everything because the other callback should now be listening to output of the not command but it was replaced by the default callback set by the cli service.

Also sorry for my bad english

**Comment by skotopes** [comment]
> > Not really. More like all changes to Furi need solid reasoning why. Usually it's some real use examples.
> 
> Alright so I'm writing an extra commands pack because I felt like the set of commands already included in the firmware lacked a lot of necessary ones. And there's the `if` command which takes two other commands as an argument and if command1 output is non-empty, it executes command2. The catch here is if we want to combine it with the `not` command which is kinda self-explanatory, both use this function and the function eventualy calls itself and if it sets the callback to default cli callback it just breaks everything because the other callback should now be listening to output of the not command but it was replaced by the default callback set by the cli service.
> 
> Also sorry for my bad english

Sounds like scripting language for CLI.

Ok, we'll accept this PR. But most likely we are not going to accept CLI scripting language.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
