### PR TITLE
HID app: added latest changes + movie and PTT

### PR DESCRIPTION
**Pull request by hryamzik**
# What's new

## HID app

- feature: added mouse acceleration by @LeeroysHub and @Willy-JL
- bugfix: improved icons and views by @krolchonok
- feature: youtube shorts support @xMasterX
- feature: movie menu, similar to media one but instead of skipping to next/previous does fast forward/backward action
- bugfix: Updated skip forward/backwards icons in `media` menu from `<<`/`>>` to `|<<`/`>>|`, meets [this](https://en.wikipedia.org/wiki/Media_control_symbols) article
- bugfix: Decreased mouse movements in mouse jigger to 1 pixel
- feature: simplified exit from some views
- feature: added PTT view for Google Meet, Zoom, Skype and FaceTime. Failed to use back button for PTT as it restarts device in ≈20 seconds. :trollface: 
- feature: removed exit confirmation dialog
- bugfix: implemented "Hold back to exit" for all the menus (except PTT)

| PushToTalk Menu | PushToTalk main view |
|-------|-----------|
|Screenshot-20231127-015626<br>Screenshot-20231127-015635|Screenshot-20231127-015829|

# Verification 

- Build with latest dev and deployed to my flipper zero device

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by hedger** [comment]
I think that with that many changes it's better to submit this app to the [app catalog](https://github.com/flipperdevices/flipper-application-catalog).

**Comment by hryamzik** [comment]
@xMasterX might agree to store it in his catalog however I can't move some changes from this repo as they don't compile with a firmware that I can't name here.

Here's the diff:
```diff
+++ b/base_pack/hid_app/hid.c
@@ -3,0 +4 @@
+#include <dolphin/dolphin.h>
@@ -316 +317 @@ void hid_hal_keyboard_press(Hid* instance, uint16_t event) {
-        furi_crash(NULL);
+        furi_crash();
@@ -327 +328 @@ void hid_hal_keyboard_release(Hid* instance, uint16_t event) {
-        furi_crash(NULL);
+        furi_crash();
@@ -338 +339 @@ void hid_hal_keyboard_release_all(Hid* instance) {
-        furi_crash(NULL);
+        furi_crash();
@@ -349 +350 @@ void hid_hal_consumer_key_press(Hid* instance, uint16_t event) {
-        furi_crash(NULL);
+        furi_crash();
@@ -360 +361 @@ void hid_hal_consumer_key_release(Hid* instance, uint16_t event) {
-        furi_crash(NULL);
+        furi_crash();
@@ -371 +372 @@ void hid_hal_consumer_key_release_all(Hid* instance) {
-        furi_crash(NULL);
+        furi_crash();
@@ -382 +383 @@ void hid_hal_mouse_move(Hid* instance, int8_t dx, int8_t dy) {
-        furi_crash(NULL);
+        furi_crash();
@@ -393 +394 @@ void hid_hal_mouse_scroll(Hid* instance, int8_t delta) {
-        furi_crash(NULL);
+        furi_crash();
@@ -404 +405 @@ void hid_hal_mouse_press(Hid* instance, uint16_t event) {
-        furi_crash(NULL);
+        furi_crash();
@@ -415 +416 @@ void hid_hal_mouse_release(Hid* instance, uint16_t event) {
-        furi_crash(NULL);
+        furi_crash();
@@ -427 +428 @@ void hid_hal_mouse_release_all(Hid* instance) {
-        furi_crash(NULL);
+        furi_crash();
@@ -440,0 +442,2 @@ int32_t hid_usb_app(void* p) {
+    dolphin_deed(DolphinDeedPluginStart);
+
@@ -472,3 +475 @@ int32_t hid_ble_app(void* p) {
-    if(!bt_set_profile(app->bt, BtProfileHidKeyboard)) {
-        FURI_LOG_E(TAG, "Failed to switch to HID profile");
-    }
+    furi_check(bt_set_profile(app->bt, BtProfileHidKeyboard));
@@ -478,0 +480,2 @@ int32_t hid_ble_app(void* p) {
+    dolphin_deed(DolphinDeedPluginStart);
+
@@ -490,3 +493 @@ int32_t hid_ble_app(void* p) {
-    if(!bt_set_profile(app->bt, BtProfileSerial)) {
-        FURI_LOG_E(TAG, "Failed to switch to Serial profile");
-    }
+    furi_check(bt_set_profile(app->bt, BtProfileSerial));
```

**Comment by hryamzik** [comment]
Oh it works with latest dev there, so could be an option.

**Comment by hryamzik** [comment]
As discussed in telegram this UI doesn't meet UX guidelines and app should be distributed separately.

I don't think it's a good idea to have 2 versions of a single app in two repos, it took me quite some time to bring it up to date here. However that's the flipper way.

**Comment by hryamzik** [comment]
Moving to draft to update UI

**Comment by hryamzik** [comment]
PushToTalk view was redesigned, waiting to be reviewed now.

**Comment by skotopes** [comment]
@hryamzik that is some serious amount of work ;-)

Are you sure that you don't want to make fork and submit it to application catalog?

Firmware release cycle is quite cumbersome thing and we also plan to take slower pace after we release 1.0. Also this app originally was not intended to be bundled with firmware, we were planning to move it to catalog, but our marketing team explicitly requested not to do that.

If you insist on merging this PR, we'll have to go throw UI/UX team first. Anyway, let me know what you think and we'll figure out next steps.

**Comment by hryamzik** [comment]
> we were planning to move it to catalog, but our marketing team explicitly requested not to do that

If the app stays in firmware I'd avoid maintaining 2 codebases. I think having a stock app and another slightly different version of it in the catalog is confusing. And passing UI/UX team review makes a lot of sense!

**Comment by hryamzik** [comment]
Resolved conflicts with #3236 and #3237

This PR had some icons changes made by @krolchonok but I don't have any opinion here, here's the difference example.






Also CC'ing @Astrrra as she was making the recent changes in dev.

UPD: and new changes are coming in #3263

**Comment by hryamzik** [comment]
nice!

**Pull request closed without merging**
