### PR TITLE
WS: Show received signal age

### PR DESCRIPTION
**Pull request by xMasterX**
Original feature by @LY2NEO with some fixes from me - [(read details)](https://github.com/DarkFlippers/unleashed-firmware/pull/197#issuecomment-1336348811)

Now rewritten to apply recommended UI changes, also contains extra change similar to #2111

# What's new

- When data is received from weather station it saves datastamp and calculates difference between actual time and data received time.
- Shows time counter on signal screen, when we reach above 1min it blinks with text [OLD], when we reach 59+ mins, it just shows [OLD]
- Now its possible to understand when signal was received if data on screen isn’t changed (for example temp stays the same)

# Verification 

- Launch Weather Station plugin, receive any supported temp sensor signal
- Select received signal and open it, check counter
- Send same signal again and see counter reset to 0

[Example_signal.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10148576/Example_signal.zip)

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
@Karator is currently preparing GUI update and then I'll merge it.

**Comment by Karator** [comment]
Hi! We have an idea of how to make this UI better and how to use free space rationally 😊
Let's move the time counter into the frame and add new icons (as shown on the screenshot)
To do so you need to stretch all the content including the frame to the screen borders and you need to add 2 new icons (small_drop and update_clock), we attached new icons here 😉
update_clock_11x11
small_drop_8x13

Thank you for your contribution 👍

image

**Comment by xMasterX** [comment]
> Hi! We have an idea of how to make this UI better and how to use free space rationally 😊 Let's move the time counter into the frame and add new icons (as shown on the screenshot) To do so you need to stretch all the content including the frame to the screen borders and you need to add 2 new icons (small_drop and update_clock), we attached new icons here 😉 update_clock_11x11 small_drop_8x13
> 
> Thank you for your contribution 👍
> 


Hi, sure, I will update PR with recommended GUI changes in next days as soon as I can

**Comment by xMasterX** [comment]
All UI changes made as requested, and ready for review

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
Couple notes:
- View were missing redraw calls and was only working because of the other apps generating GUI redraw calls in background
- Only canvas API calls allowed in view draw callback. Calling HAL or other subsystems from view draw callback makes GUI unresponsive, unpredictable and potentially can cause deadlocks
- furi_timer that updates curr_ts is the best option in this case

**Comment by xMasterX** [comment]
> Couple notes:
> 
> * View were missing redraw calls and was only working because of the other apps generating GUI redraw calls in background
> * Only canvas API calls allowed in view draw callback. Calling HAL or other subsystems from view draw callback makes GUI unresponsive, unpredictable and potentially can cause deadlocks
> * furi_timer that updates curr_ts is the best option in this case

Thanks, I will remember about this for future PR's to avoid using non canvas API calls in draw

**Pull request merged**
