### PR TITLE
Keynote BT plugin: long press on OK to switch between Space and Retur…

### PR DESCRIPTION
**Pull request by coded-with-claws**
…n (useful for Kodi)

# What's new

- Hold OK button to toggle the Keynote principal button : SPACE or ENTER. The keynote principal button will send either SPACE or ENTER accordingly.
- This adds more versatility to the Keynote plugin, in particular to control Kodi (the Kodi menu needs Enter to validate, but when playing a video, Space does play/pause and Enter opens the Playback menu which allows to stop the video.
- Please review the code
  - Especially because I added string constants in the beginning of the .c file. Is it the good way to do ?
  - I superposed the drawing of buttons on top of string texts. It works but I don't know if you are ok with that.
- Please review the GUI update with the UX designer, because I added a new indication ("Hold icon_ok : space / enter") and modified the "Hold to exit".

# Verification 

- Run BT plugin Keynote
- Hit the OK button : it sends SPACE
- Hold the OK button : on screen, the button Space becomes Enter.
- Hit the OK button : it sends ENTER
- Hold the OK button : on screen, the button Space becomes Space.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by coded-with-claws** [comment]
The "Merging is blocked" is because there was a button "Update branch" since there were commits on dev after my PR. I thought I could run the update of my PR myself :)

**Comment by skotopes** [comment]
Hi @coded-with-claws 

How about cases when someone want to press and hold space button?

**Comment by coded-with-claws** [comment]
> Hi @coded-with-claws
> 
> How about cases when someone want to press and hold space button?

Hi @skotopes 

It's not possible anymore, indeed.
Personally, I can't think of a use case about that, as the Keynote plugin is designed for presentations. To me, the "space" button is meant to validate something (flip to next slide), that's why I think it's interesting to have the possibility to send either space either return. The plugin becomes more versatile to select/validate things.

But it's my personal point of view, being a Kodi user :)
I'm not sure what is in the best interest for the community, the Keynote being a generic plugin.
I keep this evolution in my personal fork for my own needs. I thought it could be interesting for the community firmware, but I let it up to you :)

**Comment by skotopes** [comment]
@coded-with-claws I'll close this PR, it's breaking change that affects current users.

**Pull request closed without merging**
