### PR TITLE
Mifare dictionary attack performance improvements.

### PR DESCRIPTION
**Pull request by nezza**
# What's new

The dictionary attack re-activated the tag more often than is necessary - this patch improves on that. 

# Verification 

I compared behavior with multiple different cards (some for which it can find keys, some for which it can't) and saw some drastic performance improvements (1:50 to 1:14, and 27 minutes to 19 minutes).

### CODE REVIEW

**Comment by gornekich** [comment]
Hi @nezza ! Thanks for PR. 
Could you format sources? You can run ./fbt format

**Comment by nezza** [comment]
@gornekich Whoops, sorry about that! Code should be formatted now.

Thanks a lot!

**Comment by gornekich** [comment]
Hi @nezza . Tested your PR, it works fine.
I can't update you branch with latest dev. That blocks us from merging. Could you please give us access to update your branch? 
Also please don't remove task list from verification section when creating PR

**Comment by nezza** [comment]
Hey @gornekich - awesome, just gave you write access to the repository. Sorry about the task-list, I was a bit confused by the wording and thought it only applies to internal PRs

Cheers and thanks!

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
@nezza please merge dev

**Comment by skotopes** [comment]
Also you don't have to give us access to your repository itself. There were a checkbox when you were creating PR that were allowing us to sync your branch with dev.

**Comment by nezza** [comment]
Just merged in dev!

**Pull request merged**
