### PR TITLE
Furi_hal_rtc: new function

### PR DESCRIPTION
**Pull request by Leptopt1los**
# What's new

- furi_hal_rtc_timestamp_to_datetime function added

# Verification 

- build the firmware
- test the correctness of furi_hal_rtc_timestamp_to_datetime (the result furi_hal_rtc_timestamp_to_datetime (furi_hal_rtc_datetime_to_timestamp(X)) must be equals to X)

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
@Leptopt1los can you also add unit tests?

**Comment by Leptopt1los** [comment]
> @Leptopt1los can you also add unit tests?

done. sorry for the delay

**Comment by Leptopt1los** [comment]
@skotopes are there any problems with this pull request? Is anything else required on my part?

**Comment by skotopes** [comment]
nope, I'll try to merge it in this RC cycle

**Review by skotopes — APPROVED** [review]

**Pull request merged**
