### PR TITLE
Bugfix: Strip last parity bit from decoded FDX-B data

### PR DESCRIPTION
**Pull request by lagomorph**
# What's new

- Bugfix to strip the last parity bit from decoded FDX-B data. It currently stops short of the last byte.
- Added unit tests test_lfrfid_protocol_fdxb_read_simple and test_lfrfid_protocol_fdxb_emulate_simple
# Verification 

- In the common case of all zeros in the extra data section, it will currently decode as 00 00 10. It should decode as 00 00 00. With the fix, unit tests should succeed. Without the fix, test_lfrfid_protocol_fdxb_read_simple will fail:
```
test_lfrfid_protocol_fdxb_read_simple failed:
        applications/debug/unit_tests/lfrfid/lfrfid_protocols.c:535: mem not equal
        EXP  RES
        44 .. 44
        88 .. 88
        23 .. 23
        F2 .. F2
        5A .. 5A
        6F .. 6F
        00 .. 00
        01 .. 01
        00 .. 00
        00 .. 00
        00 != 10
```
# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by lagomorph** [comment]
@skotopes @DrZlo13 anything needed from me to get this reviewed?

**Comment by skotopes** [comment]
@lagomorph yep, fix is incorrect, @DrZlo13 got some ideas, but he is currently ill.

**Comment by skotopes** [comment]
will merge this PR in next release

**Comment by lagomorph** [comment]
Thanks. I don't see the issue but I'll look further.

**Review by DrZlo13 — DISMISSED** [review]

**Review by DrZlo13 — APPROVED** [review]

**Comment by DrZlo13** [comment]
Thanks for your contribution!

**Pull request merged**
