### PR TITLE
Added condition to cli "log" command to end if serial terminal is disconnected.

### PR DESCRIPTION
**Pull request by ESurge**
# What's new

- If USB is disconnected while "log" command is running, it will end the command. This is a change in cli_commands.c under cli_command_log function.

# Verification 

One way to verify:
- Connect to cli using serial terminal over USB
- Run log cli command
- Disconnect USB while log is still running
- Reconnect USB and reconnect to serial terminal over USB
- User should be prompted with normal cli prompt instead of a running log command.

Second way to verify
- Connect to cli using serial terminal over USB
- Run log cli command
- Disconnect from serial terminal while log is still running
- Reconnect to serial terminal over USB
- User should be prompted with normal cli prompt instead of a running log command.

Additional Verification:
- User should still be able to end log command using Ctrl+C break.

Note:
- If the original functionality of cli_command_log is to keep running while the serial terminal is disconnected, please feel free to decline this PR.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
Hi, how about a little bit different version: include `cli_is_connected` into `cli_cmd_interrupt_received` and return true if not connected?

**Comment by ESurge** [comment]
I reverted the change made on cli_commands.c and made the modification @skotopes suggested for the cli_cmd_interrupt_received function in cli.c.

The changes affected a lot more than the cli log command and therefore verification is a little bit more involved.

Similar verification steps should be taken, but several more cli commands should be tested.

The recent change affects the following cli commands:
- input dump
- ikey emulate
- ikey read
- ikey write
- ir rx
- log
- music_player
- nfc detect
- nfc emulate
- rfid emulate
- rfid read
- subghz chat
- subghz decode_raw
- subghz rx
- subghz tx

This change also affected the following which I cannot seem to be able to test:
- a function in unit_tests/test_index.c
- several functions in bt/bt_cli.c (bt carrier tx/rx, bt packet rx/tx) 
- a function in nfc/nfc_cli.c (nfc field)
- two functions in subghz/subghz_cli.c (carrier tx/rx)

For all the commands listed, I started the command, and tried unplugging USB and disconnecting from serial terminal.
For the subghz chat command, I used my second FlipperZero to initiate a chat between the two devices. The device that was disconnected from USB/serial terminal left chat gracefully with a message received on the other device stating as such.

**Comment by skotopes** [comment]
@ESurge Awesome work. Thanks.

**Review by skotopes — DISMISSED** [review]

**Comment by skotopes** [comment]
Please run `./fbt format` to make linter happy.

**Review by ESurge — COMMENTED** [review]
I'm not used to GitHub. I thought I had to run ./fbt format but it looks like @skotopes did - I think? So I just had to review changes and therefore I reverted the commit.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
