### PR TITLE
BadUSB: add SYSRQ keys

### LINKED ISSUE #1489: BadUSB: allow SYSRQ keys
### Describe the enhancement you're suggesting.

With the current version of the ducky script interpreter it is not possible to send [SysRq](https://en.wikipedia.org/wiki/Magic_SysRq_key) keys, which would be a very useful feature. For example it would be possible to safely reboot a frozen Linux machine or as the name "badusb" suggest be really bad in just a few characters of script.

SysRq (i.e., Alt + PRTSCR + key) can not be done with the current logic as modkeys/combinations are binary-or-ed and then sent as a single keypress. Here we have to press multiple keys. Good news is that we are free to do that by adding a new `SYSRQ` keyword to the language. This then allows a script like

```
SYSRQ b
```

to reboot a frozen box.

This is a tracking issue for what was implemented in https://github.com/flipperdevices/flipperzero-firmware/pull/1460 .

### PR DESCRIPTION
**Pull request by rck**
# What's new

This allows sending of SysRq keys[1]. This then for example allows
sending the well known 'reisub' commands to safely reboot a otherwise
frozen Linux box. Or obviously any of the other magic keys.

The advantage compared to sending it to /proc/sysrq-trigger is that one
does not need a shell and depending on how broken the system is, one
might not even be able to get a new shell. The SysRq keys still work.

The cost is adding a new/"non-standard" keyword, IMO it is worth it.

Example:
DEFAULTDELAY 200
DELAY 1000
SYSRQ r
SYSRQ e
SYSRQ i
SYSRQ s
SYSRQ u
SYSRQ b

If one really wants to test it, I suggest h(elp) or w(ait).

[1] https://en.wikipedia.org/wiki/Magic_SysRq_key

# Verification 

- rebuild firmware and test with the example on a linux box:

```
DELAY 1000
SYSRQ h
```

and then check for output in `dmesg`

Fixes #1489

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by rck** [comment]
- added a harmless verification example that prints the sysrq help to the kernel ringbuffer

**Comment by rck** [comment]
this is now lingering around over a week without any feedback. is there anything I can do that this gets reviewed/acked?

**Comment by skotopes** [comment]
@rck Hi, sorry, we are preparing release for the factory. This PR will be merged next week.

**Comment by skotopes** [comment]
Also person in charge of USB is currently on vacation, so it's taking longer time than usual.

**Comment by rck** [comment]
thanks for the update, highly appreciated. no worries, just the usual "start nagging the maintainers after a week of silence" :)

**Comment by rck** [comment]
> @rck Hi, sorry, we are preparing release for the factory. This PR will be merged next week.

It is now over a month. Any updates?

**Comment by skotopes** [comment]
Hi. Sorry for delay. We’ll merge it after elf support PR.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
