### PR TITLE
Add an AZERTY version of firmware non QWERTY uses

### PR DESCRIPTION
**Pull request by ShiroKrow**
# What's new

- Patching firmware with AZERTY support by modifing firmware/targets/furi_hal_usb_hid.h or using @Log-s version 
[[https://github.com/Log-s/flipperzero-contributions]](https://github.com/Log-s/flipperzero-contributions.git)

# Verification 

- Flipper doesn't support AZERTY keyboard for now and payloads have to be changed manually so typing "a" will put a "q" for example when injecting

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by RogueMaster** [comment]
@ShiroKrow I think you did something wrong here... also, my build doesn't have an AZERTY fix...

**Comment by ShiroKrow** [comment]
> @ShiroKrow I think you did something wrong here... also, my build doesn't have an AZERTY fix...

@RogueMaster Yes I mistook the place to ask that kind of feature. Sorry...

**Comment by hedger** [comment]
Please submit a more refined PR, not just +40k unrelated lines.

**Comment by hedger** [comment]
Keep it 1 PR = 1 feature, it's impossible to review that many changes in diffrerent subsystems & apps.

**Pull request closed without merging**
