### PR TITLE
Add lfrfid GProxII support

### PR DESCRIPTION
**Pull request by BarTenderNZ**
# What's new

Adding support for the Guardall/Verex/Chubb GProx II rfid cards. 
This can read and clone the cards. But the algorithm for the calculated XOR and CRC bits is not currently known. 
Based this off the Iceman Proxmark3 fork [cmdlfguard.c](https://github.com/RfidResearchGroup/proxmark3/blob/master/client/src/cmdlfguard.c) and added displaying XOR and CRC. 

# Verification 

I am able to read, emulate a GProxII card and write it to a T5577 

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by hedger — DISMISSED** [review]
Please run `fbt format`

**Comment by BarTenderNZ** [comment]
Thanks @hedger I had missed `fbt format` in `CODING_STYLE.md`. Apologies.

**Comment by skotopes** [comment]
@BarTenderNZ do you feel like this PR is ready to be merged?

**Comment by BarTenderNZ** [comment]
> @BarTenderNZ do you feel like this PR is ready to be merged?

Yes, I just made one last commit now so the comments don't fail the linting workflow so no longer having `XXXXXXXX` for the XOR Value.

Should now in theory pass all linting tests.

Edit. Just passed all tests. 🚀

**Review by skotopes — APPROVED** [review]

**Pull request merged**
