### PR TITLE
feat: Add up and down button drawing functions to GUI elements

### PR DESCRIPTION
**Pull request by derskythe**
Added 2 functions according to the `elements_button_left` and `elements_button_right`, but for `up` and `down` buttons.

Originally this code was made by @panki27 [Metronome](https://github.com/panki27/Metronome/issues/2).
I asked him to make PR to firmware, but have no [response](https://github.com/panki27/Metronome/issues/2)

Screenshot-20240724-060721

# What's new

- Two button drawing functions, `elements_button_up` and `elements_button_down`, have been added to the GUI elements

# Verification 

- I was made changes in [BoilerPlate app](https://github.com/derskythe/flipper-zero-fap-boilerplate)

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
This needs `furi_check(canvas);` checks added, like the other functions of this type do.

**Comment by derskythe** [comment]
@CookiePLMonster done.

**Comment by skotopes** [comment]
Can we also have some example app?

**Comment by skotopes** [comment]
Also please fix all other build errors

**Comment by panki27** [comment]
@derskythe thanks for keeping this alive!
Sorry I didn't reply, I haven't developed for the Flipper in ages.

**Comment by derskythe** [comment]
> Can we also have some example app?

@skotopes I provide the example app in PR section **Verification**
Do you need something extra? 

> Also please fix all other build errors

In your CI/CD is using version API 69.0,  but I change to 69.1 and firmware was builded in manual mode.
I don't quite understand how to fix this issue, because locally don't get any errors.

**Review by hedger — DISMISSED** [review]
Please merge dev, build both f7 and f18 targets (./fbt TARGET_HW=18) and sync API versions for them.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
