### PR TITLE
[FL-2940] WS: add protocol Ambient_Weather

### PR DESCRIPTION
**Pull request by Skorpionm**
# What's new

- [FL-2940] WS: add protocol Ambient_Weather

# Verification 

- Run the application and check the reception of the new protocol, (RAW in attached file) 
[Ambient_Weather_F007TH.zip](https://github.com/flipperdevices/flipperzero-firmware/files/9907590/Ambient_Weather_F007TH.zip)

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

[FL-2940]: https://flipperzero.atlassian.net/browse/FL-2940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by daemongloom** [comment]
Works great, thanks.

**Review by skotopes — APPROVED** [review]

**Comment by daemongloom** [comment]
Something wrong happens with negative *C temperatures. Looks like the minus sign is omitted in interface. "-0.5 *C" is shown as "00.5 *C"

**Comment by Skorpionm** [comment]
write down a raw package with a negative temperature.  need to check

**Comment by daemongloom** [comment]
[Negative.zip](https://github.com/flipperdevices/flipperzero-firmware/files/9944376/Negative.zip)
Should be 31.3 *F or -0.3888889 *C. Application shows it as 0.03 *C. So, it does not display "-" sign and seems to be truncating instead of rounding.

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/1980
check

**Comment by daemongloom** [comment]
> #1980 check

Yep, that one works fine with both positive and negative temperatures. I've tested it up to -21.7 *C.

**Comment by Skorpionm** [comment]
ok!

**Pull request merged**
