### PR TITLE
Coalesce some allocations

### PR DESCRIPTION
**Pull request by CookiePLMonster**
# What's new

This PR coalesces memory allocations done by the firmware in several places by the use of Flexible Array Members, much like it's already done in a few other places in firmware, like Message Queues. The following structures have been modified to use FAM:

* `View` - view models now are a single allocation instead of two. Memory footprint - **4 bytes (mutex ptr) + arbitrary (user) view model data**.
* `SceneManager` - array of `AppScene` coalesced with `SceneManager`. Footptint - **12 bytes? + array of scenes (4b each)**.
* `BufferStream` - array of `Buffer` coalesced with `BufferStream`. Footprint - **16 bytes + array of buffer streams (16b each)**.
* `ProtocolDict` - array of `void* dict` coalesced with `ProtocolDict`. Footptiny - **8 bytes + 4 bytes per dictionary entry**.
* `DigitalSequence` and `DigitalSignal` - data coalesced with the corresponding structs.

I verified memory usage in the main menu by rebooting the Flipper, and pressing OK once. Readings from the Release version of FW are as follows:

Before:
```
>: free
Free heap size: 141136
Total heap size: 185528
Minimum heap size: 137456
Maximum heap block: 141136
Pool free: 1368
Maximum pool block: 1340

>: free_blocks
A 2000C8E0 S 141080
```

After:
```
>: free
Free heap size: 141296
Total heap size: 185528
Minimum heap size: 140816
Maximum heap block: 141296
Pool free: 1368
Maximum pool block: 1340

>: free_blocks
A 2000C840 S 141240
```

I did not add static assets for FAMs because GCC already throws a compilation error if they are **not** the last member of the struct.

# Verification 

Verify that the menus work, and that NFC and RFID apps still work as intended.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
`free` make sense only if you remove dolphin animations

**Comment by CookiePLMonster** [comment]
> `free` make sense only if you remove dolphin animations

Done, re-did the tests with the Release version of the FW, and with all animations disabled. Now those readings look very plausible, I expected memory savings close to those readings.

**Review by hedger — CHANGES_REQUESTED** [review]
`./fbt format` please

**Comment by CookiePLMonster** [comment]
> `./fbt format` please

Done.

**Review by hedger — APPROVED** [review]

**Review by skotopes — APPROVED** [review]

**Pull request merged**
