### PR TITLE
 PicoPass / iClass

### PR DESCRIPTION
**Pull request by bettse**
# What's new

- Adds a plugin to read PicoPass / iClass cards
- Adds loclass implementation from https://github.com/RfidResearchGroup/proxmark3
- Adds mbedtls for des3 implementation

# Verification 

- To work add `picopass/iclass_key.bin` and `picopass/iclass_decryptionkey.bin` to the SD card. Both can be found in https://github.com/RfidResearchGroup/proxmark3
- Here is a video of an earlier version of it: https://twitter.com/aguynamedbettse/status/1529170304601206784

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by bettse** [comment]
Sorry for the PR dance, we wanted to change who it was being attributed to.

**Comment by RogueMaster** [comment]
Bringing in many files for this to work, are they all needed?

**Comment by PrinceAla** [comment]
So how do we get this to work on the flipper?

**Comment by bettse** [comment]
>Bringing in many files for this to work, are they all needed?

I think the bulk of the file count is the mbedtls library.  I think there are parts of it that can be excised (tests, doxygen), but removing the algorithms I'm not using would likely be technically challenging, and I don't think for long term benefit since I suspect that as more NFC protocols are added, this library will be used more often.

>So how do we get this to work on the flipper?

Please correct me if I am wrong, but from this question, in the context of a pull request, I would infer that you are not familiar with building the flipper source code and installing it.  If that is the case, I would ask that you please wait until this has been merged and is part of an official release.  I would like this pull request to stay focused on constructive conversation around getting it prepared and acceptable for inclusion in the flipper codebase, and I would like to avoid it digressing into "tech support".

**Comment by bettse** [comment]
For those without the build chain setup, here is a zip of dist/f7 for 338d0f73 : [Archive.zip](https://github.com/flipperdevices/flipperzero-firmware/files/8839074/Archive.zip)

**Comment by kevinwallace** [comment]
> I suspect that as more NFC protocols are added, this library will be used more often

+1 to this, having 3DES/AES implementations available will make DESFire emulation much easier to implement, for example.

**Comment by DrZlo13** [comment]
Embed mbedtls as a git submodule please. This will simplify the maintenance of library.

**Comment by Dygear** [comment]
This is a must have feature for many of us. I actually suspected that the original firmware would include this by default only to be disappointed. Many many thanks to @bettse for making this a reality.

**Review by DrZlo13 — DISMISSED** [review]
Embed mbedtls as a git submodule please. This will simplify the maintenance of library.

**Comment by bettse** [comment]
I added mbedtls as a submodule, but I was so excited I pushed before testing it.  I'll follow up with commits to correct problems since the version this was using isn't the latest mbedtls (3.1.0).  

In the interest of making it clear what I've done on the PR, I haven't squashed or rebased, but I'm more than happy to clean this up before it gets merged (or break it into multiple PRs: whatever leads to success)

**Comment by DrZlo13** [comment]
> I added mbedtls as a submodule, but I was so excited I pushed before testing it. I'll follow up with commits to correct problems since the version this was using isn't the latest mbedtls (3.1.0).
> 
> In the interest of making it clear what I've done on the PR, I haven't squashed or rebased, but I'm more than happy to clean this up before it gets merged (or break it into multiple PRs: whatever leads to success)

If so, please, mark this pull request as a draft.

**Comment by bettse** [comment]
I've marked it as a draft since it isn't immediately merge-able, but I would very much like any feedback on the application code, so that I can begin to address it.

**Comment by bettse** [comment]
I have still been unsuccessful at getting mbedtls working as a submodule.  Even with a flipper specific mbedtls_config.h the source code still contains a couple redundant declarations that cause the build to fail.  The least crappy solution I've come up with is wrapping those specific locations with pragma blocks (https://stackoverflow.com/a/21060076) to exclude them from the warning. I'm currently trying to find the best location in the Makefile(s) for a patch command.  I'm open to any alternative solutions if anyone has any.

**Comment by kevinwallace** [comment]
Replacing:
```makefile
C_SOURCES		+= $(wildcard $(LIB_DIR)/mbedtls/library/*.c)
```
with
```makefile
C_SOURCES		+= $(LIB_DIR)/mbedtls/library/des.c
C_SOURCES		+= $(LIB_DIR)/mbedtls/library/platform_util.c
```

in lib.mk on top of 7dfa281ef339a6c31e06ada961feabeae063d5ef worked for me.  Or, it built, at least.  I don't have any PicoPass/iClass cards nearby to test with.  Might be simpler to go that way if a full mbedtls build isn't needed yet.

**Comment by bettse** [comment]
@kevinwallace That built and works well for me, thank you for the suggestion!  If you would like some PicoPass/iClass tags, please email me (address in my profile).

**Comment by neutralinsomniac** [comment]
Where in the linked [proxmark repo](https://github.com/RfidResearchGroup/proxmark3) is `picopass/iclass_key.bin`? I only see `picopass/iclass_decryptionkey.bin`.

**Comment by skotopes** [comment]
We'll merge this PR after 0.60 release

**Comment by hedger** [comment]
Hello @bettse! We've moved to a new build system. Applications.c no longer exists, and you need an application.fam file for your app.  Check out stock apps for reference.

**Comment by kevinwallace** [comment]
Scons config to get this building again:  https://github.com/kevinwallace/flipperzero-firmware/commit/b42362ad3f535ffee0ee1adf929ba4665d96c222

**Comment by skotopes** [comment]
@bettse You did great job with this PR. Please let us know if you planing to continue this work or you need help with new build system.

**Comment by bettse** [comment]
I didn't think I'd have time to work on this, but with @kevinwallace help and a lot of community encouragement, I'm back into it.  Let me know what other changes may be required.

**Comment by bettse** [comment]
Ah, I see file conflicts, I'll fix those

**Comment by bettse** [comment]
`./fbt flash_usb --with-updater --extra-int-apps=picopass`

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
Nice work.
Let us known if you need help with UI/UX for your application. Also feel free contact me or @gornekich if you'll need anything, we really look forward to see this application as a part of firmware.

**Comment by Dygear** [comment]
@skotopes and or @gornekich is this going to ship in 0.62.0?

**Comment by IIAIronWolf** [comment]
Any chance this will be able to read iClass SE cards in the near future? Currently, the flipper can detect the card with the picopass plugin, but it says "Read Failed" "SE Enabled" at the moment.

**Comment by bettse** [comment]
> Any chance this will be able to read iClass SE cards in the near future? 

Flipper will likely follow the abilities of more advanced devices like the Proxmark3, and current the KDF and master key for SE is not public, so it is unlikely that there will be SE read support in the near future.

**Comment by strasharo** [comment]
My Flipper often freezes  (can't go back) while emulating iClass, looks like it's happening to other people I know. Where would be the appropriate place to log a bug?

**Comment by skotopes** [comment]
@strasharo https://github.com/flipperdevices/flipperzero-good-faps

**Comment by strasharo** [comment]
Thanks @skotopes , I'll do it there.

**Pull request merged**
