### PR TITLE
Overly missed feature: Infrared: move button (change button order in a remote)

### PR DESCRIPTION
**Pull request by plgcoder**
# What's new

Overly missed feature:
- change button order in a Infrared remote 

# Verification 

- create a new Infrared remote or open a saved remote > go to Button "Edit" > Submenu "Move Button" > select button to move > select new button position > Confirm "Move"

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
@plgcoder Github doesn't allow me to update your branch and merge this PR since it's not based on our repo.
You need to update it by your self, or make PR based on our repo to let github to allow us to do so.

**Comment by plgcoder** [comment]
> @plgcoder Github doesn't allow me to update your branch and merge this PR since it's not based on our repo.
> You need to update it by your self, or make PR based on our repo to let github to allow us to do so.

I updated my branch with upstream code, a little fix also.

**Comment by skotopes** [comment]
One more update required. Meanwhile I'll take PR merge pause for a couple hours.

**Comment by plgcoder** [comment]
> One more update required. Meanwhile I'll take PR merge pause for a couple hours.

Done

**Review by skotopes — APPROVED** [review]

**Pull request merged**
