### PR TITLE
Add skylanders (/activision) mifare classic to identification procedure 

### PR DESCRIPTION
**Pull request by equipter**
adds Skylanders SAK and ATQA to identification proc

used ATQA1 as necessary (previously marked as unused for Mifare classic)
added ATQA0 == 0x0F ATQA1 == 0x01 SAK == 0x01 for identification proc 

# Verification 

scan a Skylanders or infinity figurine using NFC 

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by equipter** [comment]
for reference, this comes at the request of a discord user :P they said they were gonna make an issue later so i had time to kill

**Comment by gornekich** [comment]
Hello @equipter 
Thanks for PR. Will be merged after verification on Skylanders

**Review by gornekich — CHANGES_REQUESTED** [review]
Hello @equipter 
Skylander figures came to office. After tests I notices that ATQA order check in PR is incorrect. I prepared fix here:
[change_atqa_order.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9243796/change_atqa_order.txt)
You can run git apply change_atqa_order.txt

**Comment by V0lk3n** [comment]
Hi! @gornekich, i've tested with your change as i noticed the same thing but you was more fast as me. Unfortunately there is one more change to do about the syntax used on mifare_common.c

I've made the change, compiled the FW, tested and it launch the brute force attack now!!!!!!

Here is the updated 
[change_atqa_order.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9244171/change_atqa_order.txt)

**Comment by V0lk3n** [comment]
As proof (sorry in advance if the picture are large im doing it from phone)

**Comment by V0lk3n** [comment]
> Hi! @gornekich, i've tested with your change as i noticed the same thing but you was more fast as me. Unfortunately there is one more change to do about the syntax used on mifare_common.c
> 
> I've made the change, compiled the FW, tested and it launch the brute force attack now!!!!!!
> 
> Here is the updated [change_atqa_order.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9244171/change_atqa_order.txt)

The change was about change this :

```
((ATQA0 == 0x01) && (ATQA1 == 0x0F) && (SAK == 0x01))) {//skylanders identification handling
```

To this

```
((ATQA0 == 0x01 || ATQA1 == 0x0F) && (SAK == 0x01))) { //skylanders identification handling
```

**Comment by gornekich** [comment]
Hi @V0lk3n . I managed to generate sectors keys with algorithm from web cite that you mentioned in Issue, added that keys to User dictionary and read all tag.
We will wait for changed form @equipter and merge this

**Comment by V0lk3n** [comment]
> Hi @V0lk3n . I managed to generate sectors keys with algorithm from web cite that you mentioned in Issue, added that keys to User dictionary and read all tag.
> We will wait for changed form @equipter and merge this

So cool! Thanks so much i was going to look at it xD

I ve commented into the PR, the change you mentionned need one more change in my side otherwise he keep didnt detecting it :)

**Comment by V0lk3n** [comment]
> > Hi @V0lk3n . I managed to generate sectors keys with algorithm from web cite that you mentioned in Issue, added that keys to User dictionary and read all tag.
> > We will wait for changed form @equipter and merge this
> 
> So cool! Thanks so much i was going to look at it xD
> 
> I ve commented into the PR, the change you mentionned need one more change in my side otherwise he keep didnt detecting it :)

Sorry didnt notice that it is the PR and not my issue xD

**Comment by V0lk3n** [comment]
@gornekich also, im wondering if the syntax that i changed didnt affect Mifare Desfire too?

Referencing to this:



I didnt have desfire stuff to try

**Comment by gornekich** [comment]
No changes. I add it myself #1553

**Pull request closed without merging**
