### PR TITLE
deps: add dependabot to our scripts's requirements

### PR DESCRIPTION
**Pull request by Sanix-Darker**
# What's new

- added dependabot for pip scripts
- we should be upgrading deps when it's possible

# Verification 

- N/A

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
There is a tricky part: dependencies are shipped with toolchain.

**Comment by Sanix-Darker** [comment]
Hey, thanks for a look on the PR !

> There is a tricky part: dependencies are shipped with toolchain

What does this imply clearly please ? 

This PR is just gonna make sure we have always all our scripts dependencies up to date, no security issues, newest fixes...

The CI, will confirm that we're not breaking things along the way... 🤔

**Comment by skotopes** [comment]
@Sanix-Darker normally requirements.txt should be in toolchain build scripts repository, we are currently thinking to move it there. But not decided yet. 

Probably I'll merge this PR on holidays after we decide what we going to do.

**Comment by skotopes** [comment]
Also `>=` is not good.

**Pull request closed without merging**
