### PR TITLE
Dictionary stuff: iClass keys

### PR DESCRIPTION
**Pull request by bettse**
# What's new

- Add comments to MFC dict
- Add system picopass app

# Verification 

- Run MFC read and see no problem due to comments
- open MFC dictionary and see comments

- Enable debug and logs
- Run picopass
- Run Read Card with non-standard key
- See dictionary of keys tried

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
@gornekich @bettse should we remove iclass keys from MFC dictionary?

**Comment by bettse** [comment]
> should we remove iclass keys from MFC dictionary

I wasn't aware there were iClass keys in the MFC dictionary.  iClass keys are 8 bytes, so they'd basically never work for MFC

**Comment by bettse** [comment]
The HID ones are good to keep since they are for MFC that HID supports on their multi-technology readers (multiClass, signo, etc).  they also have desfire, but I don't think the keys are leaked

**Comment by skotopes** [comment]
I guess we'll keep them then ;-)

**Comment by bettse** [comment]
yeah, they're not iClass (picopass), they are MFC keys

**Comment by skotopes** [comment]
> The HID ones are good to keep since they are for MFC that HID supports on their multi-technology readers (multiClass, signo, etc). they also have desfire, but I don't think the keys are leaked

If those keys can be found in readers we can try to extract them

**Pull request merged**
