### PR TITLE
L1_Mods animation update : adding VGM visual

### PR DESCRIPTION
**Pull request by Kuronons**
# Adding frames with Video Game Module visual to the L1_Mods ainmation

Why : In discord's VGM dedicated channel, some user proposed that the L1_Mods animation should be edited with the addition of the VGM visual. I found interesting and challenging to do so, especially making my best to respect the original animation's style. 

Changes : 
Adding 8 new .png frames + modified 4 ones to fit animation's transition.
in addition, 8 non-edited frames were renamed to fit the frame order of the anim as well as manifest.txt accordingly.

# Verification 

PR proposal validated by Valerie Aquamine via Wr3nch on official discord (VGM channel)

This is to be REVIEWED and EDITED by VALERIE AQUAMINE.
Expecting some slight edits to fit the official Flipper's animations standards.

# Checklist (For Reviewer)

New frames and edited frames : from frame_21.png to frame_32.png (total 12 frames)
Frames 33 to 48 were previously the frames 22 to 40 and have not been visually edited.

Visual additions / Edits :
- VGM module with led fx (frames 21 to 29)
- Upper screen : Adding letter D (frames 23 to 32)
- Upper screen : modified arrows and "text lines" (frames 23 to 32)
- Upper screen : modified 9999 to KURO as signature/wink -> I expect this might be reverted to original or else... (frames 23 to 32)
- Lower screen : Space Invaders inspired design instead of signal wave (frames 23 to 27)
- Manifest.txt : adding the 8 new frames in frame order + setting passive frame number accordingly

### CODE REVIEW

**Comment by skotopes** [comment]
@Kuronons 

Sorry for delay, here is a comment from our art team: 

`Upper screen : modified 9999 to KURO as signature/wink -> I expect this might be reverted to original or else... (frames 23 to 32)` - please revert to MOD999

**Comment by skotopes** [comment]
Undraft when ready and I'll merge it

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
@Kuronons nice!)

**Comment by Kuronons** [comment]
> @Kuronons nice!)

Thanks ! :)

**Pull request merged**
