### PR TITLE
Decode RAW recordings

### PR DESCRIPTION
**Pull request by qistoph**
# What's new

Flipper_SubGhz_RAW_decoder-2022-08-26_21 36 43

- Add `decode` to the More menu of saved RAW recordings
- Reuses the SubGhz Receiver View
- Tweaked this view to support:
  - Live versus File view
  - File progress (instead of Config button) in left bottom
- Reuses the SubGhz Receiver Info scene
- Add `subghz_file_encoder_worker_get_text_progress`

The icon could use a little improvement. Unfortunately I'm not a fluent designer.
assets/icons/SubGhz/Decoding_123x52.png

# Verification 

- Make a RAW recording of signals supported by available decoders
- Save the RAW recording
- From a saved RAW recording, open the `More` menu
- Select the `Decode` option
- See how Flipper decodes the recorded signals

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by skotopes** [comment]
Hi. We already have it as a cli command and intentionally decided not to make GUI version of it.

Is there any real life use cases for it?

**Comment by azaitsev** [comment]
@skotopes as for me it's cool to have it in gui

**Comment by qistoph** [comment]
While new protocol support is still being developed, it's a great way to test support for previously recorded codes.

I also feel, like @azaitsev, it should be part of the interface. It will also help beginner users to more easily understand and try-out the relationship between raw recordings and their decoded counter parts.

**Comment by white-gecko** [comment]
> Hi. We already have it as a cli command and intentionally decided not to make GUI version of it.
> 
> Is there any real life use cases for it?
> @skotopes

Could you please point to the respective CLI?

**Comment by qistoph** [comment]
> Could you please point to the respective CLI?

Checkout my comment in the related issue: https://github.com/flipperdevices/flipperzero-firmware/issues/1638#issuecomment-1223560058

**Comment by RogueMaster** [comment]
I definitely like it better in the GUI

**Comment by HenryDorsettC4se** [comment]
I second this. Some of us cannot use the cli often and, some of us, cannot use the phone app at all (I do not have enough money to buy a new phone and my old one is not supported :/)
The GUI/Onboard possibility to decode raw encodings is awesome imo.

**Comment by jagotu** [comment]
I also very much like this feature. Unlike the CLI command, it creates an output in a format you can save. With the CLI, you'd have to take the text output and manually convert it into the .sub file format.

For me this feature is useful where you want to limit the time "in the field", for example when recording doorbells, as you can only trigger the bell twice (record raw and then try if the recording works), and then use this UI to decode the recording or even decode it later once the protocol gets added. If you were to start with non-raw recordings and the protocol was unsupported, you increase the number of recording attempts you have to make.

All-in-all for me this is a very nice additition to the FW.

**Comment by skotopes** [comment]
Hi. Sorry for long delay. 

We started to split SubGhz application into specialized apps and can accept this PR as external application. Would you like to try to make this feature separate app?

**Review by skotopes — CHANGES_REQUESTED** [review]
See comments in PR thread

**Comment by skotopes** [comment]
I'll move this PR to draft, please un-draft when you complete.

**Comment by CodyTolene** [comment]
Any updates on this?

**Comment by skotopes** [comment]
@CodyTolene at this point the best option to implement whole thing as external application.

**Pull request closed without merging**
