### PR TITLE
Iclass UI

### PR DESCRIPTION
**Pull request by bettse**
# What's new

- Adds scene to Picopass plugin

Other notes:

 - This was _heavily_ based on the NFC app
 - includes some storage references to set the stage for saving/downgrading to LF HID Prox
 - It is a shit ton of code, but the minimal amount I could do to replicate the existing functionality.
 - As always, let me know of any changes I need to make
 - `./fbt flash_usb --with-updater --extra-int-apps=picopass `

# Verification 

- Launch Picopass plugin
- Select "Read Card"
- Put Flipper near iClass credential
- Hear chime, see success screen, see raw credential (and decoded if 26 bit)

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by RogueMaster** [comment]
#1365 seems to use lib/mbedtls.scons, but it is getting removed here... dunno which one is correct but one will need to change I think

**Comment by ezhevita** [comment]
My pull request need mbedtls for nfc_protocols
anyway it's possible to reference one module from another, so I don't think it would be a problem

**Comment by skotopes** [comment]
```
6380786 [I][LoaderSrv]: Application thread stopped. Free heap: 125664. Thread allocation balance: 88.
6381097 [I][AnimationManager]: Select 'L1_Furippa1_128x64' animation
6381101 [I][AnimationManager]: Load animation 'L1_Furippa1_128x64'
6381103 [I][SavedStruct]: Loading "/int/desktop.settings"
6394174 [I][LoaderSrv]: Starting: PicoPass Reader
6394180 [I][AnimationManager]: Unload animation 'L1_Furippa1_128x64'
6396180 [I][LoaderSrv]: Application thread stopped. Free heap: 125576. Thread allocation balance: 88.
6396492 [I][AnimationManager]: Select 'L1_Furippa1_128x64' animation
6396494 [I][AnimationManager]: Load animation 'L1_Furippa1_128x64'
6396496 [I][SavedStruct]: Loading "/int/desktop.settings"
6400567 [I][LoaderSrv]: Starting: PicoPass Reader
6400573 [I][AnimationManager]: Unload animation 'L1_Furippa1_128x64'
6401581 [I][LoaderSrv]: Application thread stopped. Free heap: 125488. Thread allocation balance: 88.
```

Leaking memory

**Comment by skotopes** [comment]
missing `picopass_device_free` call

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
Please take a look on https://github.com/flipperdevices/flipperzero-firmware/pull/1366/commits/487e1bc56fbe81c9088a9c885b60b21a653136c0

Since C doesn't have namespaces we create them artificially by prefixing types and functions with package name.
I've cleaned up picopass application, but loclass lib is require some work.

**Pull request merged**
